#ifndef __XACT_PROJECT_REVOLT__
#define __XACT_PROJECT_REVOLT__

typedef enum
{
    XACT_WAVEBANK_COMMON_WBOMBHIT = 0,
    XACT_WAVEBANK_COMMON_BALL = 1,
    XACT_WAVEBANK_COMMON_BALLDROP = 2,
    XACT_WAVEBANK_COMMON_BEACHBALL = 3,
    XACT_WAVEBANK_COMMON_BOTTLE = 4,
    XACT_WAVEBANK_COMMON_BOXSLIDE = 5,
    XACT_WAVEBANK_COMMON_CLOCKWRK = 6,
    XACT_WAVEBANK_COMMON_COUNTDOWN = 7,
    XACT_WAVEBANK_COMMON_ELECTRO = 8,
    XACT_WAVEBANK_COMMON_ELECTROZAP = 9,
    XACT_WAVEBANK_COMMON_FIREBANG = 10,
    XACT_WAVEBANK_COMMON_FIREFIRE = 11,
    XACT_WAVEBANK_COMMON_FUSE = 12,
    XACT_WAVEBANK_COMMON_HIT1 = 13,
    XACT_WAVEBANK_COMMON_HIT2 = 14,
    XACT_WAVEBANK_COMMON_HONKA = 15,
    XACT_WAVEBANK_COMMON_HONKGOOD = 16,
    XACT_WAVEBANK_COMMON_LIGHTFLK = 17,
    XACT_WAVEBANK_COMMON_MENULEFTRIGHT = 18,
    XACT_WAVEBANK_COMMON_MENUNEXT = 19,
    XACT_WAVEBANK_COMMON_MENUPREV = 20,
    XACT_WAVEBANK_COMMON_MENUUPDOWN = 21,
    XACT_WAVEBANK_COMMON_MOTO = 22,
    XACT_WAVEBANK_COMMON_OILDROP = 23,
    XACT_WAVEBANK_COMMON_PETROL = 24,
    XACT_WAVEBANK_COMMON_PICKGEN = 25,
    XACT_WAVEBANK_COMMON_PICKUP = 26,
    XACT_WAVEBANK_COMMON_PUTTBANG = 27,
    XACT_WAVEBANK_COMMON_SCRAPE = 28,
    XACT_WAVEBANK_COMMON_SERVO = 29,
    XACT_WAVEBANK_COMMON_SHOCK = 30,
    XACT_WAVEBANK_COMMON_SHOCKFIRE = 31,
    XACT_WAVEBANK_COMMON_SKID_NORMAL = 32,
    XACT_WAVEBANK_COMMON_SKID_ROUGH = 33,
    XACT_WAVEBANK_COMMON_SPLASH = 34,
    XACT_WAVEBANK_COMMON_STARFIRE = 35,
    XACT_WAVEBANK_COMMON_TURBO = 36,
    XACT_WAVEBANK_COMMON_TVSTATIC = 37,
    XACT_WAVEBANK_COMMON_UFO = 38,
    XACT_WAVEBANK_COMMON_WBOMB = 39,
    XACT_WAVEBANK_COMMON_WBOMBBOUNCE = 40,
    XACT_WAVEBANK_COMMON_WBOMBFIRE = 41,
} XACT_WAVEBANK_COMMON;

#define XACT_WAVEBANK_COMMON_ENTRY_COUNT 42

typedef enum
{
    XACT_WAVEBANK_GARDEN1_ANIMAL1 = 0,
    XACT_WAVEBANK_GARDEN1_ANIMAL2 = 1,
    XACT_WAVEBANK_GARDEN1_ANIMAL3 = 2,
    XACT_WAVEBANK_GARDEN1_ANIMAL4 = 3,
    XACT_WAVEBANK_GARDEN1_STREAM = 4,
    XACT_WAVEBANK_GARDEN1_TROPICS2 = 5,
    XACT_WAVEBANK_GARDEN1_TROPICS3 = 6,
    XACT_WAVEBANK_GARDEN1_TROPICS4 = 7,
} XACT_WAVEBANK_GARDEN1;

#define XACT_WAVEBANK_GARDEN1_ENTRY_COUNT 8

typedef enum
{
    XACT_WAVEBANK_MARKAR_AIRCOND1 = 0,
    XACT_WAVEBANK_MARKAR_CABNHUM2 = 1,
    XACT_WAVEBANK_MARKAR_CARPARK = 2,
    XACT_WAVEBANK_MARKAR_CARTON = 3,
    XACT_WAVEBANK_MARKAR_FREEZER1 = 4,
    XACT_WAVEBANK_MARKAR_ICEYAREA = 5,
    XACT_WAVEBANK_MARKAR_SDRSCLOS = 6,
    XACT_WAVEBANK_MARKAR_SDRSOPEN = 7,
} XACT_WAVEBANK_MARKAR;

#define XACT_WAVEBANK_MARKAR_ENTRY_COUNT 8

typedef enum
{
    XACT_WAVEBANK_MARKET1_AIRCOND1 = 0,
    XACT_WAVEBANK_MARKET1_CABNHUM2 = 1,
    XACT_WAVEBANK_MARKET1_CARPARK = 2,
    XACT_WAVEBANK_MARKET1_CARTON = 3,
    XACT_WAVEBANK_MARKET1_FREEZER1 = 4,
    XACT_WAVEBANK_MARKET1_ICEYAREA = 5,
    XACT_WAVEBANK_MARKET1_SDRSCLOS = 6,
    XACT_WAVEBANK_MARKET1_SDRSOPEN = 7,
} XACT_WAVEBANK_MARKET1;

#define XACT_WAVEBANK_MARKET1_ENTRY_COUNT 8

typedef enum
{
    XACT_WAVEBANK_MARKET2_AIRCOND1 = 0,
    XACT_WAVEBANK_MARKET2_CABNHUM2 = 1,
    XACT_WAVEBANK_MARKET2_CARPARK = 2,
    XACT_WAVEBANK_MARKET2_CARTON = 3,
    XACT_WAVEBANK_MARKET2_FREEZER1 = 4,
    XACT_WAVEBANK_MARKET2_ICEYAREA = 5,
    XACT_WAVEBANK_MARKET2_SDRSCLOS = 6,
    XACT_WAVEBANK_MARKET2_SDRSOPEN = 7,
} XACT_WAVEBANK_MARKET2;

#define XACT_WAVEBANK_MARKET2_ENTRY_COUNT 8

typedef enum
{
    XACT_WAVEBANK_MUSE1_ALARM2 = 0,
    XACT_WAVEBANK_MUSE1_ESCALATE = 1,
    XACT_WAVEBANK_MUSE1_LARGDOOR = 2,
    XACT_WAVEBANK_MUSE1_LASERHUM = 3,
    XACT_WAVEBANK_MUSE1_MUSEUMAM = 4,
    XACT_WAVEBANK_MUSE1_ROTATING = 5,
} XACT_WAVEBANK_MUSE1;

#define XACT_WAVEBANK_MUSE1_ENTRY_COUNT 6

typedef enum
{
    XACT_WAVEBANK_MUSE2_ALARM2 = 0,
    XACT_WAVEBANK_MUSE2_ESCALATE = 1,
    XACT_WAVEBANK_MUSE2_LARGDOOR = 2,
    XACT_WAVEBANK_MUSE2_LASERHUM = 3,
    XACT_WAVEBANK_MUSE2_MUSEUMAM = 4,
    XACT_WAVEBANK_MUSE2_ROTATING = 5,
} XACT_WAVEBANK_MUSE2;

#define XACT_WAVEBANK_MUSE2_ENTRY_COUNT 6

typedef enum
{
    XACT_WAVEBANK_MUSE_BAT_ALARM2 = 0,
    XACT_WAVEBANK_MUSE_BAT_ESCALATE = 1,
    XACT_WAVEBANK_MUSE_BAT_LARGDOOR = 2,
    XACT_WAVEBANK_MUSE_BAT_LASERHUM = 3,
    XACT_WAVEBANK_MUSE_BAT_MUSEUMAM = 4,
    XACT_WAVEBANK_MUSE_BAT_ROTATING = 5,
} XACT_WAVEBANK_MUSE_BAT;

#define XACT_WAVEBANK_MUSE_BAT_ENTRY_COUNT 6

typedef enum
{
    XACT_WAVEBANK_NHOOD1_BASKETBALL = 0,
    XACT_WAVEBANK_NHOOD1_BIRDS1 = 1,
    XACT_WAVEBANK_NHOOD1_BIRDS2 = 2,
    XACT_WAVEBANK_NHOOD1_BIRDS3 = 3,
    XACT_WAVEBANK_NHOOD1_CITYAMB2 = 4,
    XACT_WAVEBANK_NHOOD1_DIGGER = 5,
    XACT_WAVEBANK_NHOOD1_DOGBARK = 6,
    XACT_WAVEBANK_NHOOD1_KIDS = 7,
    XACT_WAVEBANK_NHOOD1_LAWNMOWER = 8,
    XACT_WAVEBANK_NHOOD1_ROADCONE = 9,
    XACT_WAVEBANK_NHOOD1_SPRINK = 10,
    XACT_WAVEBANK_NHOOD1_STREAM = 11,
    XACT_WAVEBANK_NHOOD1_TV = 12,
} XACT_WAVEBANK_NHOOD1;

#define XACT_WAVEBANK_NHOOD1_ENTRY_COUNT 13

typedef enum
{
    XACT_WAVEBANK_NHOOD1_BATTLE_BASKETBALL = 0,
    XACT_WAVEBANK_NHOOD1_BATTLE_BIRDS1 = 1,
    XACT_WAVEBANK_NHOOD1_BATTLE_BIRDS2 = 2,
    XACT_WAVEBANK_NHOOD1_BATTLE_BIRDS3 = 3,
    XACT_WAVEBANK_NHOOD1_BATTLE_CITYAMB2 = 4,
    XACT_WAVEBANK_NHOOD1_BATTLE_DIGGER = 5,
    XACT_WAVEBANK_NHOOD1_BATTLE_DOGBARK = 6,
    XACT_WAVEBANK_NHOOD1_BATTLE_KIDS = 7,
    XACT_WAVEBANK_NHOOD1_BATTLE_LAWNMOWER = 8,
    XACT_WAVEBANK_NHOOD1_BATTLE_ROADCONE = 9,
    XACT_WAVEBANK_NHOOD1_BATTLE_SPRINK = 10,
    XACT_WAVEBANK_NHOOD1_BATTLE_STREAM = 11,
    XACT_WAVEBANK_NHOOD1_BATTLE_TV = 12,
} XACT_WAVEBANK_NHOOD1_BATTLE;

#define XACT_WAVEBANK_NHOOD1_BATTLE_ENTRY_COUNT 13

typedef enum
{
    XACT_WAVEBANK_NHOOD2_BASKETBALL = 0,
    XACT_WAVEBANK_NHOOD2_BIRDS1 = 1,
    XACT_WAVEBANK_NHOOD2_BIRDS2 = 2,
    XACT_WAVEBANK_NHOOD2_BIRDS3 = 3,
    XACT_WAVEBANK_NHOOD2_CITYAMB2 = 4,
    XACT_WAVEBANK_NHOOD2_DIGGER = 5,
    XACT_WAVEBANK_NHOOD2_DOGBARK = 6,
    XACT_WAVEBANK_NHOOD2_KIDS = 7,
    XACT_WAVEBANK_NHOOD2_LAWNMOWER = 8,
    XACT_WAVEBANK_NHOOD2_ROADCONE = 9,
    XACT_WAVEBANK_NHOOD2_SPRINK = 10,
    XACT_WAVEBANK_NHOOD2_STREAM = 11,
    XACT_WAVEBANK_NHOOD2_TV = 12,
} XACT_WAVEBANK_NHOOD2;

#define XACT_WAVEBANK_NHOOD2_ENTRY_COUNT 13

typedef enum
{
    XACT_WAVEBANK_SHIP1_INTAMB1 = 0,
    XACT_WAVEBANK_SHIP1_SEAGULLS = 1,
    XACT_WAVEBANK_SHIP1_SHIPHORN = 2,
    XACT_WAVEBANK_SHIP1_STRMRAIN = 3,
    XACT_WAVEBANK_SHIP1_THUNDER1 = 4,
    XACT_WAVEBANK_SHIP1_WASH = 5,
} XACT_WAVEBANK_SHIP1;

#define XACT_WAVEBANK_SHIP1_ENTRY_COUNT 6

typedef enum
{
    XACT_WAVEBANK_SHIP2_INTAMB1 = 0,
    XACT_WAVEBANK_SHIP2_SEAGULLS = 1,
    XACT_WAVEBANK_SHIP2_SHIPHORN = 2,
    XACT_WAVEBANK_SHIP2_STRMRAIN = 3,
    XACT_WAVEBANK_SHIP2_THUNDER1 = 4,
    XACT_WAVEBANK_SHIP2_WASH = 5,
} XACT_WAVEBANK_SHIP2;

#define XACT_WAVEBANK_SHIP2_ENTRY_COUNT 6

typedef enum
{
    XACT_WAVEBANK_TOY2_ARCADE = 0,
    XACT_WAVEBANK_TOY2_COPTER = 1,
    XACT_WAVEBANK_TOY2_CREAK = 2,
    XACT_WAVEBANK_TOY2_DRAGON = 3,
    XACT_WAVEBANK_TOY2_PIANO = 4,
    XACT_WAVEBANK_TOY2_PLANE = 5,
    XACT_WAVEBANK_TOY2_TOYBRICK = 6,
    XACT_WAVEBANK_TOY2_TRAIN = 7,
    XACT_WAVEBANK_TOY2_WHISTLE = 8,
} XACT_WAVEBANK_TOY2;

#define XACT_WAVEBANK_TOY2_ENTRY_COUNT 9

typedef enum
{
    XACT_WAVEBANK_TOYLITE_ARCADE = 0,
    XACT_WAVEBANK_TOYLITE_COPTER = 1,
    XACT_WAVEBANK_TOYLITE_CREAK = 2,
    XACT_WAVEBANK_TOYLITE_DRAGON = 3,
    XACT_WAVEBANK_TOYLITE_PIANO = 4,
    XACT_WAVEBANK_TOYLITE_PLANE = 5,
    XACT_WAVEBANK_TOYLITE_TOYBRICK = 6,
    XACT_WAVEBANK_TOYLITE_TRAIN = 7,
    XACT_WAVEBANK_TOYLITE_WHISTLE = 8,
} XACT_WAVEBANK_TOYLITE;

#define XACT_WAVEBANK_TOYLITE_ENTRY_COUNT 9

typedef enum
{
    XACT_WAVEBANK_WILD_WEST1_BATS = 0,
    XACT_WAVEBANK_WILD_WEST1_COYOTE1 = 1,
    XACT_WAVEBANK_WILD_WEST1_EAGLE1 = 2,
    XACT_WAVEBANK_WILD_WEST1_MINEDRIP = 3,
    XACT_WAVEBANK_WILD_WEST1_RATTLER = 4,
    XACT_WAVEBANK_WILD_WEST1_TOWNBELL = 5,
    XACT_WAVEBANK_WILD_WEST1_TUMBWEED = 6,
} XACT_WAVEBANK_WILD_WEST1;

#define XACT_WAVEBANK_WILD_WEST1_ENTRY_COUNT 7

typedef enum
{
    XACT_WAVEBANK_WILD_WEST2_BATS = 0,
    XACT_WAVEBANK_WILD_WEST2_COYOTE1 = 1,
    XACT_WAVEBANK_WILD_WEST2_EAGLE1 = 2,
    XACT_WAVEBANK_WILD_WEST2_MINEDRIP = 3,
    XACT_WAVEBANK_WILD_WEST2_RATTLER = 4,
    XACT_WAVEBANK_WILD_WEST2_TOWNBELL = 5,
    XACT_WAVEBANK_WILD_WEST2_TUMBWEED = 6,
} XACT_WAVEBANK_WILD_WEST2;

#define XACT_WAVEBANK_WILD_WEST2_ENTRY_COUNT 7

typedef enum
{
    XACT_SOUNDBANK_COMMON_BALL = 0,
    XACT_SOUNDBANK_COMMON_BALLDROP = 1,
    XACT_SOUNDBANK_COMMON_BEACHBALL = 2,
    XACT_SOUNDBANK_COMMON_BOTTLE = 3,
    XACT_SOUNDBANK_COMMON_BOXSLIDE = 4,
    XACT_SOUNDBANK_COMMON_CLOCKWORK = 5,
    XACT_SOUNDBANK_COMMON_COUNTDOWN = 6,
    XACT_SOUNDBANK_COMMON_ELECTRO = 7,
    XACT_SOUNDBANK_COMMON_ELECTROZAP = 8,
    XACT_SOUNDBANK_COMMON_FIREWORKBANG = 9,
    XACT_SOUNDBANK_COMMON_FIREWORKFIRE = 10,
    XACT_SOUNDBANK_COMMON_FUSE = 11,
    XACT_SOUNDBANK_COMMON_HIT1 = 12,
    XACT_SOUNDBANK_COMMON_HIT2 = 13,
    XACT_SOUNDBANK_COMMON_HONKA = 14,
    XACT_SOUNDBANK_COMMON_HONKGOOD = 15,
    XACT_SOUNDBANK_COMMON_LIGHTFLK = 16,
    XACT_SOUNDBANK_COMMON_MENULEFTRIGHT = 17,
    XACT_SOUNDBANK_COMMON_MENUNEXT = 18,
    XACT_SOUNDBANK_COMMON_MENUPREV = 19,
    XACT_SOUNDBANK_COMMON_MENUUPDOWN = 20,
    XACT_SOUNDBANK_COMMON_MOTOR = 21,
    XACT_SOUNDBANK_COMMON_OILDROP = 22,
    XACT_SOUNDBANK_COMMON_PETROL = 23,
    XACT_SOUNDBANK_COMMON_PICKUPGEN = 24,
    XACT_SOUNDBANK_COMMON_PICKUP = 25,
    XACT_SOUNDBANK_COMMON_PUTTYBOMBBANG = 26,
    XACT_SOUNDBANK_COMMON_SCRAPE = 27,
    XACT_SOUNDBANK_COMMON_SERVO = 28,
    XACT_SOUNDBANK_COMMON_SHOCK = 29,
    XACT_SOUNDBANK_COMMON_SHOCKFIRE = 30,
    XACT_SOUNDBANK_COMMON_SKIDNORMAL = 31,
    XACT_SOUNDBANK_COMMON_SKIDROUGH = 32,
    XACT_SOUNDBANK_COMMON_SPLASH = 33,
    XACT_SOUNDBANK_COMMON_STARFIRE = 34,
    XACT_SOUNDBANK_COMMON_TURBO = 35,
    XACT_SOUNDBANK_COMMON_TVSTATIC = 36,
    XACT_SOUNDBANK_COMMON_UFO = 37,
    XACT_SOUNDBANK_COMMON_WATERBOMB = 38,
    XACT_SOUNDBANK_COMMON_WATERBOMBBOUNCE = 39,
    XACT_SOUNDBANK_COMMON_WATERBOMBFIRE = 40,
    XACT_SOUNDBANK_COMMON_WATERBOMBHIT = 41,
    XACT_SOUNDBANK_COMMON_BGMUSIC = 42,
    XACT_SOUNDBANK_COMMON_SPLASH_LOOPING = 43,
    XACT_SOUNDBANK_COMMON_COUNTDOWN_HIGH = 44,
} XACT_SOUNDBANK_COMMON;

#define XACT_SOUNDBANK_COMMON_CUE_COUNT 45

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_GARDEN_ANIMAL1 = 0,
    XACT_SOUNDBANK_GARDEN1_GARDEN_ANIMAL2 = 1,
    XACT_SOUNDBANK_GARDEN1_GARDEN_ANIMAL3 = 2,
    XACT_SOUNDBANK_GARDEN1_GARDEN_ANIMAL4 = 3,
    XACT_SOUNDBANK_GARDEN1_GARDEN_STREAM = 4,
    XACT_SOUNDBANK_GARDEN1_GARDEN_TROPICS2 = 5,
    XACT_SOUNDBANK_GARDEN1_GARDEN_TROPICS3 = 6,
    XACT_SOUNDBANK_GARDEN1_GARDEN_TROPICS4 = 7,
} XACT_SOUNDBANK_GARDEN1;

#define XACT_SOUNDBANK_GARDEN1_CUE_COUNT 8

typedef enum
{
    XACT_SOUNDBANK_MARKAR_MARKET_AIRCOND1 = 0,
    XACT_SOUNDBANK_MARKAR_MARKET_CABNHUM2 = 1,
    XACT_SOUNDBANK_MARKAR_MARKET_CARPARK = 2,
    XACT_SOUNDBANK_MARKAR_MARKET_CARTON = 3,
    XACT_SOUNDBANK_MARKAR_MARKET_FREEZER1 = 4,
    XACT_SOUNDBANK_MARKAR_MARKET_ICEYAREA = 5,
    XACT_SOUNDBANK_MARKAR_MARKET_SDRSCLOS = 6,
    XACT_SOUNDBANK_MARKAR_MARKET_SDRSOPEN = 7,
} XACT_SOUNDBANK_MARKAR;

#define XACT_SOUNDBANK_MARKAR_CUE_COUNT 8

typedef enum
{
    XACT_SOUNDBANK_MARKET1_MARKET_AIRCOND1 = 0,
    XACT_SOUNDBANK_MARKET1_MARKET_CABNHUM2 = 1,
    XACT_SOUNDBANK_MARKET1_MARKET_CARPARK = 2,
    XACT_SOUNDBANK_MARKET1_MARKET_CARTON = 3,
    XACT_SOUNDBANK_MARKET1_MARKET_FREEZER1 = 4,
    XACT_SOUNDBANK_MARKET1_MARKET_ICEYAREA = 5,
    XACT_SOUNDBANK_MARKET1_MARKET_SDRSCLOS = 6,
    XACT_SOUNDBANK_MARKET1_MARKET_SDRSOPEN = 7,
} XACT_SOUNDBANK_MARKET1;

#define XACT_SOUNDBANK_MARKET1_CUE_COUNT 8

typedef enum
{
    XACT_SOUNDBANK_MARKET2_MARKET_AIRCOND1 = 0,
    XACT_SOUNDBANK_MARKET2_MARKET_CABNHUM2 = 1,
    XACT_SOUNDBANK_MARKET2_MARKET_CARPARK = 2,
    XACT_SOUNDBANK_MARKET2_MARKET_CARTON = 3,
    XACT_SOUNDBANK_MARKET2_MARKET_FREEZER1 = 4,
    XACT_SOUNDBANK_MARKET2_MARKET_ICEYAREA = 5,
    XACT_SOUNDBANK_MARKET2_MARKET_SDRSCLOS = 6,
    XACT_SOUNDBANK_MARKET2_MARKET_SDRSOPEN = 7,
} XACT_SOUNDBANK_MARKET2;

#define XACT_SOUNDBANK_MARKET2_CUE_COUNT 8

typedef enum
{
    XACT_SOUNDBANK_MUSE1_MUSEUM_ALARM2 = 0,
    XACT_SOUNDBANK_MUSE1_MUSEUM_ESCALATE = 1,
    XACT_SOUNDBANK_MUSE1_MUSEUM_LARGDOOR = 2,
    XACT_SOUNDBANK_MUSE1_MUSEUM_LASERHUM = 3,
    XACT_SOUNDBANK_MUSE1_MUSEUM_MUSEUMAM = 4,
    XACT_SOUNDBANK_MUSE1_MUSEUM_ROTATING = 5,
} XACT_SOUNDBANK_MUSE1;

#define XACT_SOUNDBANK_MUSE1_CUE_COUNT 6

typedef enum
{
    XACT_SOUNDBANK_MUSE2_MUSEUM_ALARM2 = 0,
    XACT_SOUNDBANK_MUSE2_MUSEUM_ESCALATE = 1,
    XACT_SOUNDBANK_MUSE2_MUSEUM_LARGDOOR = 2,
    XACT_SOUNDBANK_MUSE2_MUSEUM_LASERHUM = 3,
    XACT_SOUNDBANK_MUSE2_MUSEUM_MUSEUMAM = 4,
    XACT_SOUNDBANK_MUSE2_MUSEUM_ROTATING = 5,
} XACT_SOUNDBANK_MUSE2;

#define XACT_SOUNDBANK_MUSE2_CUE_COUNT 6

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_MUSEUM_ALARM2 = 0,
    XACT_SOUNDBANK_MUSE_BAT_MUSEUM_ESCALATE = 1,
    XACT_SOUNDBANK_MUSE_BAT_MUSEUM_LARGDOOR = 2,
    XACT_SOUNDBANK_MUSE_BAT_MUSEUM_LASERHUM = 3,
    XACT_SOUNDBANK_MUSE_BAT_MUSEUM_MUSEUMAM = 4,
    XACT_SOUNDBANK_MUSE_BAT_MUSEUM_ROTATING = 5,
} XACT_SOUNDBANK_MUSE_BAT;

#define XACT_SOUNDBANK_MUSE_BAT_CUE_COUNT 6

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_HOOD_BASKETBALL = 0,
    XACT_SOUNDBANK_NHOOD1_HOOD_BIRDS1 = 1,
    XACT_SOUNDBANK_NHOOD1_HOOD_BIRDS2 = 2,
    XACT_SOUNDBANK_NHOOD1_HOOD_BIRDS3 = 3,
    XACT_SOUNDBANK_NHOOD1_HOOD_CITYAMB2 = 4,
    XACT_SOUNDBANK_NHOOD1_HOOD_DIGGER = 5,
    XACT_SOUNDBANK_NHOOD1_HOOD_DOGBARK = 6,
    XACT_SOUNDBANK_NHOOD1_HOOD_KIDS = 7,
    XACT_SOUNDBANK_NHOOD1_HOOD_LAWNMOWER = 8,
    XACT_SOUNDBANK_NHOOD1_HOOD_ROADCONE = 9,
    XACT_SOUNDBANK_NHOOD1_HOOD_SPRINK = 10,
    XACT_SOUNDBANK_NHOOD1_HOOD_HOODSTREAM = 11,
    XACT_SOUNDBANK_NHOOD1_HOOD_TV = 12,
} XACT_SOUNDBANK_NHOOD1;

#define XACT_SOUNDBANK_NHOOD1_CUE_COUNT 13

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_BASKETBALL = 0,
    XACT_SOUNDBANK_NHOOD1_BATTLE_BIRDS1 = 1,
    XACT_SOUNDBANK_NHOOD1_BATTLE_BIRDS2 = 2,
    XACT_SOUNDBANK_NHOOD1_BATTLE_BIRDS3 = 3,
    XACT_SOUNDBANK_NHOOD1_BATTLE_CITYAMB2 = 4,
    XACT_SOUNDBANK_NHOOD1_BATTLE_DIGGER = 5,
    XACT_SOUNDBANK_NHOOD1_BATTLE_DOGBARK = 6,
    XACT_SOUNDBANK_NHOOD1_BATTLE_KIDS = 7,
    XACT_SOUNDBANK_NHOOD1_BATTLE_LAWNMOWER = 8,
    XACT_SOUNDBANK_NHOOD1_BATTLE_ROADCONE = 9,
    XACT_SOUNDBANK_NHOOD1_BATTLE_SPRINK = 10,
    XACT_SOUNDBANK_NHOOD1_BATTLE_STREAM = 11,
    XACT_SOUNDBANK_NHOOD1_BATTLE_TV = 12,
} XACT_SOUNDBANK_NHOOD1_BATTLE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_COUNT 13

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_BASKETBALL = 0,
    XACT_SOUNDBANK_NHOOD2_BIRDS1 = 1,
    XACT_SOUNDBANK_NHOOD2_BIRDS2 = 2,
    XACT_SOUNDBANK_NHOOD2_BIRDS3 = 3,
    XACT_SOUNDBANK_NHOOD2_CITYAMB2 = 4,
    XACT_SOUNDBANK_NHOOD2_DIGGER = 5,
    XACT_SOUNDBANK_NHOOD2_DOGBARK = 6,
    XACT_SOUNDBANK_NHOOD2_KIDS = 7,
    XACT_SOUNDBANK_NHOOD2_LAWNMOWER = 8,
    XACT_SOUNDBANK_NHOOD2_ROADCONE = 9,
    XACT_SOUNDBANK_NHOOD2_SPRINK = 10,
    XACT_SOUNDBANK_NHOOD2_STREAM = 11,
    XACT_SOUNDBANK_NHOOD2_TV = 12,
} XACT_SOUNDBANK_NHOOD2;

#define XACT_SOUNDBANK_NHOOD2_CUE_COUNT 13

typedef enum
{
    XACT_SOUNDBANK_SHIP1_SHIP_INTAMB1 = 0,
    XACT_SOUNDBANK_SHIP1_SHIP_SEAGULLS = 1,
    XACT_SOUNDBANK_SHIP1_SHIP_SHIPHORN = 2,
    XACT_SOUNDBANK_SHIP1_SHIP_STRMRAIN = 3,
    XACT_SOUNDBANK_SHIP1_SHIP_THUNDER1 = 4,
    XACT_SOUNDBANK_SHIP1_SHIP_WASH = 5,
} XACT_SOUNDBANK_SHIP1;

#define XACT_SOUNDBANK_SHIP1_CUE_COUNT 6

typedef enum
{
    XACT_SOUNDBANK_SHIP2_INTAMB1 = 0,
    XACT_SOUNDBANK_SHIP2_SEAGULLS = 1,
    XACT_SOUNDBANK_SHIP2_SHIPHORN = 2,
    XACT_SOUNDBANK_SHIP2_STRMRAIN = 3,
    XACT_SOUNDBANK_SHIP2_THUNDER1 = 4,
    XACT_SOUNDBANK_SHIP2_WASH = 5,
} XACT_SOUNDBANK_SHIP2;

#define XACT_SOUNDBANK_SHIP2_CUE_COUNT 6

typedef enum
{
    XACT_SOUNDBANK_TOY2_TOY_ARCADE = 0,
    XACT_SOUNDBANK_TOY2_TOY_COPTER = 1,
    XACT_SOUNDBANK_TOY2_TOY_CREAK = 2,
    XACT_SOUNDBANK_TOY2_TOY_DRAGON = 3,
    XACT_SOUNDBANK_TOY2_TOY_PIANO = 4,
    XACT_SOUNDBANK_TOY2_TOY_PLANE = 5,
    XACT_SOUNDBANK_TOY2_TOY_TOYBRICK = 6,
    XACT_SOUNDBANK_TOY2_TOY_TRAIN = 7,
    XACT_SOUNDBANK_TOY2_TOY_WHISTLE = 8,
} XACT_SOUNDBANK_TOY2;

#define XACT_SOUNDBANK_TOY2_CUE_COUNT 9

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_ARCADE = 0,
    XACT_SOUNDBANK_TOYLITE_COPTER = 1,
    XACT_SOUNDBANK_TOYLITE_CREAK = 2,
    XACT_SOUNDBANK_TOYLITE_DRAGON = 3,
    XACT_SOUNDBANK_TOYLITE_PIANO = 4,
    XACT_SOUNDBANK_TOYLITE_PLANE = 5,
    XACT_SOUNDBANK_TOYLITE_TOYBRICK = 6,
    XACT_SOUNDBANK_TOYLITE_TRAIN = 7,
    XACT_SOUNDBANK_TOYLITE_WHISTLE = 8,
} XACT_SOUNDBANK_TOYLITE;

#define XACT_SOUNDBANK_TOYLITE_CUE_COUNT 9

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_GHOST_BATS = 0,
    XACT_SOUNDBANK_WILD_WEST1_GHOST_COYOTE1 = 1,
    XACT_SOUNDBANK_WILD_WEST1_GHOST_EAGLE1 = 2,
    XACT_SOUNDBANK_WILD_WEST1_GHOST_MINEDRIP = 3,
    XACT_SOUNDBANK_WILD_WEST1_GHOST_RATTLER = 4,
    XACT_SOUNDBANK_WILD_WEST1_GHOST_TOWNBELL = 5,
    XACT_SOUNDBANK_WILD_WEST1_GHOST_TUMBWEED = 6,
} XACT_SOUNDBANK_WILD_WEST1;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_COUNT 7

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_BATS = 0,
    XACT_SOUNDBANK_WILD_WEST2_COYOTE1 = 1,
    XACT_SOUNDBANK_WILD_WEST2_EAGLE1 = 2,
    XACT_SOUNDBANK_WILD_WEST2_MINEDRIP = 3,
    XACT_SOUNDBANK_WILD_WEST2_RATTLER = 4,
    XACT_SOUNDBANK_WILD_WEST2_TOWNBELL = 5,
    XACT_SOUNDBANK_WILD_WEST2_TUMBWEED = 6,
} XACT_SOUNDBANK_WILD_WEST2;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_COUNT 7

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_BALL_SOUND_BALL = 0,
} XACT_SOUNDBANK_COMMON_CUE_BALL_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_BALL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_BALLDROP_SOUND_BALLDROP = 0,
} XACT_SOUNDBANK_COMMON_CUE_BALLDROP_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_BALLDROP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_BEACHBALL_SOUND_BEACHBALL = 0,
} XACT_SOUNDBANK_COMMON_CUE_BEACHBALL_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_BEACHBALL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_BOTTLE_SOUND_BOTTLE = 0,
} XACT_SOUNDBANK_COMMON_CUE_BOTTLE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_BOTTLE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_BOXSLIDE_SOUND_BOXSLIDE = 0,
} XACT_SOUNDBANK_COMMON_CUE_BOXSLIDE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_BOXSLIDE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_CLOCKWORK_SOUND_CLOCKWRK = 0,
} XACT_SOUNDBANK_COMMON_CUE_CLOCKWORK_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_CLOCKWORK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_COUNTDOWN_SOUND_COUNTDOWN = 0,
} XACT_SOUNDBANK_COMMON_CUE_COUNTDOWN_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_COUNTDOWN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_ELECTRO_SOUND_ELECTRO = 0,
} XACT_SOUNDBANK_COMMON_CUE_ELECTRO_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_ELECTRO_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_ELECTROZAP_SOUND_ELECTROZAP = 0,
} XACT_SOUNDBANK_COMMON_CUE_ELECTROZAP_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_ELECTROZAP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_FIREWORKBANG_SOUND_FIREBANG = 0,
} XACT_SOUNDBANK_COMMON_CUE_FIREWORKBANG_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_FIREWORKBANG_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_FIREWORKFIRE_SOUND_FIREFIRE = 0,
} XACT_SOUNDBANK_COMMON_CUE_FIREWORKFIRE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_FIREWORKFIRE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_FUSE_SOUND_FUSE = 0,
} XACT_SOUNDBANK_COMMON_CUE_FUSE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_FUSE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_HIT1_SOUND_HIT1 = 0,
} XACT_SOUNDBANK_COMMON_CUE_HIT1_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_HIT1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_HIT2_SOUND_HIT2 = 0,
} XACT_SOUNDBANK_COMMON_CUE_HIT2_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_HIT2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_HONKA_SOUND_HONKA = 0,
} XACT_SOUNDBANK_COMMON_CUE_HONKA_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_HONKA_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_HONKGOOD_SOUND_HONKGOOD = 0,
} XACT_SOUNDBANK_COMMON_CUE_HONKGOOD_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_HONKGOOD_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_LIGHTFLK_SOUND_LIGHTFLK = 0,
} XACT_SOUNDBANK_COMMON_CUE_LIGHTFLK_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_LIGHTFLK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_MENULEFTRIGHT_SOUND_MENULEFTRIGHT = 0,
} XACT_SOUNDBANK_COMMON_CUE_MENULEFTRIGHT_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_MENULEFTRIGHT_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_MENUNEXT_SOUND_MENUNEXT = 0,
} XACT_SOUNDBANK_COMMON_CUE_MENUNEXT_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_MENUNEXT_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_MENUPREV_SOUND_MENUPREV = 0,
} XACT_SOUNDBANK_COMMON_CUE_MENUPREV_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_MENUPREV_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_MENUUPDOWN_SOUND_MENUUPDOWN = 0,
} XACT_SOUNDBANK_COMMON_CUE_MENUUPDOWN_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_MENUUPDOWN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_MOTOR_SOUND_MOTO = 0,
} XACT_SOUNDBANK_COMMON_CUE_MOTOR_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_MOTOR_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_OILDROP_SOUND_OILDROP = 0,
} XACT_SOUNDBANK_COMMON_CUE_OILDROP_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_OILDROP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_PETROL_SOUND_PETROL = 0,
} XACT_SOUNDBANK_COMMON_CUE_PETROL_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_PETROL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_PICKUPGEN_SOUND_PICKGEN = 0,
} XACT_SOUNDBANK_COMMON_CUE_PICKUPGEN_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_PICKUPGEN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_PICKUP_SOUND_PICKUP = 0,
} XACT_SOUNDBANK_COMMON_CUE_PICKUP_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_PICKUP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_PUTTYBOMBBANG_SOUND_PUTTBANG = 0,
} XACT_SOUNDBANK_COMMON_CUE_PUTTYBOMBBANG_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_PUTTYBOMBBANG_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SCRAPE_SOUND_SCRAPE = 0,
} XACT_SOUNDBANK_COMMON_CUE_SCRAPE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SCRAPE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SERVO_SOUND_SERVO = 0,
} XACT_SOUNDBANK_COMMON_CUE_SERVO_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SERVO_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SHOCK_SOUND_SHOCK = 0,
} XACT_SOUNDBANK_COMMON_CUE_SHOCK_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SHOCK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SHOCKFIRE_SOUND_SHOCKFIRE = 0,
} XACT_SOUNDBANK_COMMON_CUE_SHOCKFIRE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SHOCKFIRE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SKIDNORMAL_SOUND_SKID_NORMAL = 0,
} XACT_SOUNDBANK_COMMON_CUE_SKIDNORMAL_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SKIDNORMAL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SKIDROUGH_SOUND_SKID_ROUGH = 0,
} XACT_SOUNDBANK_COMMON_CUE_SKIDROUGH_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SKIDROUGH_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SPLASH_SOUND_SPLASH = 0,
} XACT_SOUNDBANK_COMMON_CUE_SPLASH_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SPLASH_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_STARFIRE_SOUND_STARFIRE = 0,
} XACT_SOUNDBANK_COMMON_CUE_STARFIRE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_STARFIRE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_TURBO_SOUND_TURBO = 0,
} XACT_SOUNDBANK_COMMON_CUE_TURBO_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_TURBO_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_TVSTATIC_SOUND_TVSTATIC = 0,
} XACT_SOUNDBANK_COMMON_CUE_TVSTATIC_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_TVSTATIC_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_UFO_SOUND_UFO = 0,
} XACT_SOUNDBANK_COMMON_CUE_UFO_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_UFO_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_WATERBOMB_SOUND_WBOMB = 0,
} XACT_SOUNDBANK_COMMON_CUE_WATERBOMB_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_WATERBOMB_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_WATERBOMBBOUNCE_SOUND_WBOMBBOUNCE = 0,
} XACT_SOUNDBANK_COMMON_CUE_WATERBOMBBOUNCE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_WATERBOMBBOUNCE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_WATERBOMBFIRE_SOUND_WBOMBFIRE = 0,
} XACT_SOUNDBANK_COMMON_CUE_WATERBOMBFIRE_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_WATERBOMBFIRE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_WATERBOMBHIT_SOUND_WBOMBHIT = 0,
} XACT_SOUNDBANK_COMMON_CUE_WATERBOMBHIT_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_WATERBOMBHIT_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_BGMUSIC_SOUND_BGMUSIC = 0,
} XACT_SOUNDBANK_COMMON_CUE_BGMUSIC_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_BGMUSIC_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_SPLASH_LOOPING_SOUND_SPLASH_LOOPING = 0,
} XACT_SOUNDBANK_COMMON_CUE_SPLASH_LOOPING_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_SPLASH_LOOPING_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_CUE_COUNTDOWN_HIGH_SOUND_COUNTDOWN_HIGH = 0,
} XACT_SOUNDBANK_COMMON_CUE_COUNTDOWN_HIGH_SOUND;

#define XACT_SOUNDBANK_COMMON_CUE_COUNTDOWN_HIGH_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL1_SOUND_ANIMAL1 = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL1_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL2_SOUND_ANIMAL2 = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL2_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL3_SOUND_ANIMAL3 = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL3_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL4_SOUND_ANIMAL4 = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL4_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_ANIMAL4_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_STREAM_SOUND_STREAM = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_STREAM_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_STREAM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS2_SOUND_TROPICS2 = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS2_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS3_SOUND_TROPICS3 = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS3_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS4_SOUND_TROPICS4 = 0,
} XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS4_SOUND;

#define XACT_SOUNDBANK_GARDEN1_CUE_GARDEN_TROPICS4_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_AIRCOND1_SOUND_AIRCOND1 = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_AIRCOND1_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_AIRCOND1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_CABNHUM2_SOUND_CABNHUM2 = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_CABNHUM2_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_CABNHUM2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_CARPARK_SOUND_CARPARK = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_CARPARK_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_CARPARK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_CARTON_SOUND_CARTON = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_CARTON_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_CARTON_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_FREEZER1_SOUND_FREEZER1 = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_FREEZER1_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_FREEZER1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_ICEYAREA_SOUND_ICEYAREA = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_ICEYAREA_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_ICEYAREA_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_SDRSCLOS_SOUND_SDRSCLOS = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_SDRSCLOS_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_SDRSCLOS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_CUE_MARKET_SDRSOPEN_SOUND_SDRSOPEN = 0,
} XACT_SOUNDBANK_MARKAR_CUE_MARKET_SDRSOPEN_SOUND;

#define XACT_SOUNDBANK_MARKAR_CUE_MARKET_SDRSOPEN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_AIRCOND1_SOUND_AIRCOND1 = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_AIRCOND1_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_AIRCOND1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_CABNHUM2_SOUND_CABNHUM2 = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_CABNHUM2_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_CABNHUM2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_CARPARK_SOUND_CARPARK = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_CARPARK_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_CARPARK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_CARTON_SOUND_CARTON = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_CARTON_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_CARTON_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_FREEZER1_SOUND_FREEZER1 = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_FREEZER1_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_FREEZER1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_ICEYAREA_SOUND_ICEYAREA = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_ICEYAREA_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_ICEYAREA_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_SDRSCLOS_SOUND_SDRSCLOS = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_SDRSCLOS_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_SDRSCLOS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_CUE_MARKET_SDRSOPEN_SOUND_SDRSOPEN = 0,
} XACT_SOUNDBANK_MARKET1_CUE_MARKET_SDRSOPEN_SOUND;

#define XACT_SOUNDBANK_MARKET1_CUE_MARKET_SDRSOPEN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_AIRCOND1_SOUND_AIRCOND1 = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_AIRCOND1_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_AIRCOND1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_CABNHUM2_SOUND_CABNHUM2 = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_CABNHUM2_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_CABNHUM2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_CARPARK_SOUND_CARPARK = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_CARPARK_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_CARPARK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_CARTON_SOUND_CARTON = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_CARTON_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_CARTON_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_FREEZER1_SOUND_FREEZER1 = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_FREEZER1_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_FREEZER1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_ICEYAREA_SOUND_ICEYAREA = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_ICEYAREA_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_ICEYAREA_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_SDRSCLOS_SOUND_SDRSCLOS = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_SDRSCLOS_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_SDRSCLOS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_CUE_MARKET_SDRSOPEN_SOUND_SDRSOPEN = 0,
} XACT_SOUNDBANK_MARKET2_CUE_MARKET_SDRSOPEN_SOUND;

#define XACT_SOUNDBANK_MARKET2_CUE_MARKET_SDRSOPEN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ALARM2_SOUND_ALARM2 = 0,
} XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ALARM2_SOUND;

#define XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ALARM2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ESCALATE_SOUND_ESCALATE = 0,
} XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ESCALATE_SOUND;

#define XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ESCALATE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_LARGDOOR_SOUND_LARGDOOR = 0,
} XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_LARGDOOR_SOUND;

#define XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_LARGDOOR_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_LASERHUM_SOUND_LASERHUM = 0,
} XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_LASERHUM_SOUND;

#define XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_LASERHUM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_MUSEUMAM_SOUND_MUSEUMAM = 0,
} XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_MUSEUMAM_SOUND;

#define XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_MUSEUMAM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ROTATING_SOUND_ROTATING = 0,
} XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ROTATING_SOUND;

#define XACT_SOUNDBANK_MUSE1_CUE_MUSEUM_ROTATING_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ALARM2_SOUND_ALARM2 = 0,
} XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ALARM2_SOUND;

#define XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ALARM2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ESCALATE_SOUND_ESCALATE = 0,
} XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ESCALATE_SOUND;

#define XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ESCALATE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_LARGDOOR_SOUND_LARGDOOR = 0,
} XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_LARGDOOR_SOUND;

#define XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_LARGDOOR_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_LASERHUM_SOUND_LASERHUM = 0,
} XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_LASERHUM_SOUND;

#define XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_LASERHUM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_MUSEUMAM_SOUND_MUSEUMAM = 0,
} XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_MUSEUMAM_SOUND;

#define XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_MUSEUMAM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ROTATING_SOUND_ROTATING = 0,
} XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ROTATING_SOUND;

#define XACT_SOUNDBANK_MUSE2_CUE_MUSEUM_ROTATING_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ALARM2_SOUND_ALARM2 = 0,
} XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ALARM2_SOUND;

#define XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ALARM2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ESCALATE_SOUND_ESCALATE = 0,
} XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ESCALATE_SOUND;

#define XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ESCALATE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_LARGDOOR_SOUND_LARGDOOR = 0,
} XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_LARGDOOR_SOUND;

#define XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_LARGDOOR_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_LASERHUM_SOUND_LASERHUM = 0,
} XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_LASERHUM_SOUND;

#define XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_LASERHUM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_MUSEUMAM_SOUND_MUSEUMAM = 0,
} XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_MUSEUMAM_SOUND;

#define XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_MUSEUMAM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ROTATING_SOUND_ROTATING = 0,
} XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ROTATING_SOUND;

#define XACT_SOUNDBANK_MUSE_BAT_CUE_MUSEUM_ROTATING_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BASKETBALL_SOUND_BASKETBALL = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BASKETBALL_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BASKETBALL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS1_SOUND_BIRDS1 = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS1_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS2_SOUND_BIRDS2 = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS2_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS3_SOUND_BIRDS3 = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS3_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_BIRDS3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_CITYAMB2_SOUND_CITYAMB2 = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_CITYAMB2_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_CITYAMB2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_DIGGER_SOUND_DIGGER = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_DIGGER_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_DIGGER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_DOGBARK_SOUND_DOGBARK = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_DOGBARK_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_DOGBARK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_KIDS_SOUND_KIDS = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_KIDS_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_KIDS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_LAWNMOWER_SOUND_LAWNMOWER = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_LAWNMOWER_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_LAWNMOWER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_ROADCONE_SOUND_ROADCONE = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_ROADCONE_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_ROADCONE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_SPRINK_SOUND_SPRINK = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_SPRINK_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_SPRINK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_HOODSTREAM_SOUND_STREAM = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_HOODSTREAM_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_HOODSTREAM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_CUE_HOOD_TV_SOUND_TV = 0,
} XACT_SOUNDBANK_NHOOD1_CUE_HOOD_TV_SOUND;

#define XACT_SOUNDBANK_NHOOD1_CUE_HOOD_TV_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BASKETBALL_SOUND_BASKETBALL = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BASKETBALL_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BASKETBALL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS1_SOUND_BIRDS1 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS1_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS2_SOUND_BIRDS2 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS2_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS3_SOUND_BIRDS3 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS3_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_BIRDS3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_CITYAMB2_SOUND_CITYAMB2 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_CITYAMB2_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_CITYAMB2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_DIGGER_SOUND_DIGGER = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_DIGGER_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_DIGGER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_DOGBARK_SOUND_DOGBARK = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_DOGBARK_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_DOGBARK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_KIDS_SOUND_KIDS = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_KIDS_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_KIDS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_LAWNMOWER_SOUND_LAWNMOWER = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_LAWNMOWER_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_LAWNMOWER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_ROADCONE_SOUND_ROADCONE = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_ROADCONE_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_ROADCONE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_SPRINK_SOUND_SPRINK = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_SPRINK_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_SPRINK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_STREAM_SOUND_STREAM = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_STREAM_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_STREAM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_TV_SOUND_TV = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_TV_SOUND;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_CUE_TV_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_BASKETBALL_SOUND_BASKETBALL = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_BASKETBALL_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_BASKETBALL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_BIRDS1_SOUND_BIRDS1 = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_BIRDS1_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_BIRDS1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_BIRDS2_SOUND_BIRDS2 = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_BIRDS2_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_BIRDS2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_BIRDS3_SOUND_BIRDS3 = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_BIRDS3_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_BIRDS3_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_CITYAMB2_SOUND_CITYAMB2 = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_CITYAMB2_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_CITYAMB2_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_DIGGER_SOUND_DIGGER = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_DIGGER_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_DIGGER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_DOGBARK_SOUND_DOGBARK = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_DOGBARK_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_DOGBARK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_KIDS_SOUND_KIDS = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_KIDS_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_KIDS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_LAWNMOWER_SOUND_LAWNMOWER = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_LAWNMOWER_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_LAWNMOWER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_ROADCONE_SOUND_ROADCONE = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_ROADCONE_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_ROADCONE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_SPRINK_SOUND_SPRINK = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_SPRINK_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_SPRINK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_STREAM_SOUND_STREAM = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_STREAM_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_STREAM_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_CUE_TV_SOUND_TV = 0,
} XACT_SOUNDBANK_NHOOD2_CUE_TV_SOUND;

#define XACT_SOUNDBANK_NHOOD2_CUE_TV_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_CUE_SHIP_INTAMB1_SOUND_INTAMB1 = 0,
} XACT_SOUNDBANK_SHIP1_CUE_SHIP_INTAMB1_SOUND;

#define XACT_SOUNDBANK_SHIP1_CUE_SHIP_INTAMB1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_CUE_SHIP_SEAGULLS_SOUND_SEAGULLS = 0,
} XACT_SOUNDBANK_SHIP1_CUE_SHIP_SEAGULLS_SOUND;

#define XACT_SOUNDBANK_SHIP1_CUE_SHIP_SEAGULLS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_CUE_SHIP_SHIPHORN_SOUND_SHIPHORN = 0,
} XACT_SOUNDBANK_SHIP1_CUE_SHIP_SHIPHORN_SOUND;

#define XACT_SOUNDBANK_SHIP1_CUE_SHIP_SHIPHORN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_CUE_SHIP_STRMRAIN_SOUND_STRMRAIN = 0,
} XACT_SOUNDBANK_SHIP1_CUE_SHIP_STRMRAIN_SOUND;

#define XACT_SOUNDBANK_SHIP1_CUE_SHIP_STRMRAIN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_CUE_SHIP_THUNDER1_SOUND_THUNDER1 = 0,
} XACT_SOUNDBANK_SHIP1_CUE_SHIP_THUNDER1_SOUND;

#define XACT_SOUNDBANK_SHIP1_CUE_SHIP_THUNDER1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_CUE_SHIP_WASH_SOUND_WASH = 0,
} XACT_SOUNDBANK_SHIP1_CUE_SHIP_WASH_SOUND;

#define XACT_SOUNDBANK_SHIP1_CUE_SHIP_WASH_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_CUE_INTAMB1_SOUND_INTAMB1 = 0,
} XACT_SOUNDBANK_SHIP2_CUE_INTAMB1_SOUND;

#define XACT_SOUNDBANK_SHIP2_CUE_INTAMB1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_CUE_SEAGULLS_SOUND_SEAGULLS = 0,
} XACT_SOUNDBANK_SHIP2_CUE_SEAGULLS_SOUND;

#define XACT_SOUNDBANK_SHIP2_CUE_SEAGULLS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_CUE_SHIPHORN_SOUND_SHIPHORN = 0,
} XACT_SOUNDBANK_SHIP2_CUE_SHIPHORN_SOUND;

#define XACT_SOUNDBANK_SHIP2_CUE_SHIPHORN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_CUE_STRMRAIN_SOUND_STRMRAIN = 0,
} XACT_SOUNDBANK_SHIP2_CUE_STRMRAIN_SOUND;

#define XACT_SOUNDBANK_SHIP2_CUE_STRMRAIN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_CUE_THUNDER1_SOUND_THUNDER1 = 0,
} XACT_SOUNDBANK_SHIP2_CUE_THUNDER1_SOUND;

#define XACT_SOUNDBANK_SHIP2_CUE_THUNDER1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_CUE_WASH_SOUND_WASH = 0,
} XACT_SOUNDBANK_SHIP2_CUE_WASH_SOUND;

#define XACT_SOUNDBANK_SHIP2_CUE_WASH_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_ARCADE_SOUND_ARCADE = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_ARCADE_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_ARCADE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_COPTER_SOUND_COPTER = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_COPTER_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_COPTER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_CREAK_SOUND_CREAK = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_CREAK_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_CREAK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_DRAGON_SOUND_DRAGON = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_DRAGON_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_DRAGON_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_PIANO_SOUND_PIANO = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_PIANO_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_PIANO_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_PLANE_SOUND_PLANE = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_PLANE_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_PLANE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_TOYBRICK_SOUND_TOYBRICK = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_TOYBRICK_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_TOYBRICK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_TRAIN_SOUND_TRAIN = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_TRAIN_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_TRAIN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_CUE_TOY_WHISTLE_SOUND_WHISTLE = 0,
} XACT_SOUNDBANK_TOY2_CUE_TOY_WHISTLE_SOUND;

#define XACT_SOUNDBANK_TOY2_CUE_TOY_WHISTLE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_ARCADE_SOUND_ARCADE = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_ARCADE_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_ARCADE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_COPTER_SOUND_COPTER = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_COPTER_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_COPTER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_CREAK_SOUND_CREAK = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_CREAK_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_CREAK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_DRAGON_SOUND_DRAGON = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_DRAGON_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_DRAGON_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_PIANO_SOUND_PIANO = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_PIANO_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_PIANO_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_PLANE_SOUND_PLANE = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_PLANE_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_PLANE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_TOYBRICK_SOUND_TOYBRICK = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_TOYBRICK_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_TOYBRICK_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_TRAIN_SOUND_TRAIN = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_TRAIN_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_TRAIN_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_CUE_WHISTLE_SOUND_WHISTLE = 0,
} XACT_SOUNDBANK_TOYLITE_CUE_WHISTLE_SOUND;

#define XACT_SOUNDBANK_TOYLITE_CUE_WHISTLE_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_BATS_SOUND_BATS = 0,
} XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_BATS_SOUND;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_BATS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_COYOTE1_SOUND_COYOTE1 = 0,
} XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_COYOTE1_SOUND;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_COYOTE1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_EAGLE1_SOUND_EAGLE1 = 0,
} XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_EAGLE1_SOUND;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_EAGLE1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_MINEDRIP_SOUND_MINEDRIP = 0,
} XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_MINEDRIP_SOUND;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_MINEDRIP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_RATTLER_SOUND_RATTLER = 0,
} XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_RATTLER_SOUND;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_RATTLER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_TOWNBELL_SOUND_TOWNBELL = 0,
} XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_TOWNBELL_SOUND;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_TOWNBELL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_TUMBWEED_SOUND_TUMBWEED = 0,
} XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_TUMBWEED_SOUND;

#define XACT_SOUNDBANK_WILD_WEST1_CUE_GHOST_TUMBWEED_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_CUE_BATS_SOUND_BATS = 0,
} XACT_SOUNDBANK_WILD_WEST2_CUE_BATS_SOUND;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_BATS_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_CUE_COYOTE1_SOUND_COYOTE1 = 0,
} XACT_SOUNDBANK_WILD_WEST2_CUE_COYOTE1_SOUND;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_COYOTE1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_CUE_EAGLE1_SOUND_EAGLE1 = 0,
} XACT_SOUNDBANK_WILD_WEST2_CUE_EAGLE1_SOUND;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_EAGLE1_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_CUE_MINEDRIP_SOUND_MINEDRIP = 0,
} XACT_SOUNDBANK_WILD_WEST2_CUE_MINEDRIP_SOUND;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_MINEDRIP_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_CUE_RATTLER_SOUND_RATTLER = 0,
} XACT_SOUNDBANK_WILD_WEST2_CUE_RATTLER_SOUND;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_RATTLER_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_CUE_TOWNBELL_SOUND_TOWNBELL = 0,
} XACT_SOUNDBANK_WILD_WEST2_CUE_TOWNBELL_SOUND;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_TOWNBELL_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_CUE_TUMBWEED_SOUND_TUMBWEED = 0,
} XACT_SOUNDBANK_WILD_WEST2_CUE_TUMBWEED_SOUND;

#define XACT_SOUNDBANK_WILD_WEST2_CUE_TUMBWEED_SOUND_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_BALL_TRACK_0_WAVE_BALL = 0,
} XACT_SOUNDBANK_COMMON_SOUND_BALL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_BALL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_BALLDROP_TRACK_0_WAVE_BALLDROP = 0,
} XACT_SOUNDBANK_COMMON_SOUND_BALLDROP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_BALLDROP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_BEACHBALL_TRACK_0_WAVE_BEACHBALL = 0,
} XACT_SOUNDBANK_COMMON_SOUND_BEACHBALL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_BEACHBALL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_BOTTLE_TRACK_0_WAVE_BOTTLE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_BOTTLE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_BOTTLE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_BOXSLIDE_TRACK_0_WAVE_BOXSLIDE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_BOXSLIDE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_BOXSLIDE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_CLOCKWRK_TRACK_0_WAVE_CLOCKWRK = 0,
} XACT_SOUNDBANK_COMMON_SOUND_CLOCKWRK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_CLOCKWRK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_COUNTDOWN_TRACK_0_WAVE_COUNTDOWN = 0,
} XACT_SOUNDBANK_COMMON_SOUND_COUNTDOWN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_COUNTDOWN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_ELECTRO_TRACK_0_WAVE_ELECTRO = 0,
} XACT_SOUNDBANK_COMMON_SOUND_ELECTRO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_ELECTRO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_ELECTROZAP_TRACK_0_WAVE_ELECTROZAP = 0,
} XACT_SOUNDBANK_COMMON_SOUND_ELECTROZAP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_ELECTROZAP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_FIREBANG_TRACK_0_WAVE_FIREBANG = 0,
} XACT_SOUNDBANK_COMMON_SOUND_FIREBANG_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_FIREBANG_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_FIREFIRE_TRACK_0_WAVE_FIREFIRE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_FIREFIRE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_FIREFIRE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_FUSE_TRACK_0_WAVE_FUSE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_FUSE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_FUSE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_HIT1_TRACK_0_WAVE_HIT1 = 0,
} XACT_SOUNDBANK_COMMON_SOUND_HIT1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_HIT1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_HIT2_TRACK_0_WAVE_HIT2 = 0,
} XACT_SOUNDBANK_COMMON_SOUND_HIT2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_HIT2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_HONKA_TRACK_0_WAVE_HONKA = 0,
} XACT_SOUNDBANK_COMMON_SOUND_HONKA_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_HONKA_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_HONKGOOD_TRACK_0_WAVE_HONKGOOD = 0,
} XACT_SOUNDBANK_COMMON_SOUND_HONKGOOD_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_HONKGOOD_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_LIGHTFLK_TRACK_0_WAVE_LIGHTFLK = 0,
} XACT_SOUNDBANK_COMMON_SOUND_LIGHTFLK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_LIGHTFLK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_MENULEFTRIGHT_TRACK_0_WAVE_MENULEFTRIGHT = 0,
} XACT_SOUNDBANK_COMMON_SOUND_MENULEFTRIGHT_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_MENULEFTRIGHT_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_MENUNEXT_TRACK_0_WAVE_MENUNEXT = 0,
} XACT_SOUNDBANK_COMMON_SOUND_MENUNEXT_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_MENUNEXT_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_MENUPREV_TRACK_0_WAVE_MENUPREV = 0,
} XACT_SOUNDBANK_COMMON_SOUND_MENUPREV_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_MENUPREV_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_MENUUPDOWN_TRACK_0_WAVE_MENUUPDOWN = 0,
} XACT_SOUNDBANK_COMMON_SOUND_MENUUPDOWN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_MENUUPDOWN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_MOTO_TRACK_0_WAVE_MOTO = 0,
} XACT_SOUNDBANK_COMMON_SOUND_MOTO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_MOTO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_OILDROP_TRACK_0_WAVE_OILDROP = 0,
} XACT_SOUNDBANK_COMMON_SOUND_OILDROP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_OILDROP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_PETROL_TRACK_0_WAVE_PETROL = 0,
} XACT_SOUNDBANK_COMMON_SOUND_PETROL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_PETROL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_PICKGEN_TRACK_0_WAVE_PICKGEN = 0,
} XACT_SOUNDBANK_COMMON_SOUND_PICKGEN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_PICKGEN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_PICKUP_TRACK_0_WAVE_PICKUP = 0,
} XACT_SOUNDBANK_COMMON_SOUND_PICKUP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_PICKUP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_PUTTBANG_TRACK_0_WAVE_PUTTBANG = 0,
} XACT_SOUNDBANK_COMMON_SOUND_PUTTBANG_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_PUTTBANG_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SCRAPE_TRACK_0_WAVE_SCRAPE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SCRAPE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SCRAPE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SERVO_TRACK_0_WAVE_SERVO = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SERVO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SERVO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SHOCK_TRACK_0_WAVE_SHOCK = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SHOCK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SHOCK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SHOCKFIRE_TRACK_0_WAVE_SHOCKFIRE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SHOCKFIRE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SHOCKFIRE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SKID_NORMAL_TRACK_0_WAVE_SKID_NORMAL = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SKID_NORMAL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SKID_NORMAL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SKID_ROUGH_TRACK_0_WAVE_SKID_ROUGH = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SKID_ROUGH_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SKID_ROUGH_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SPLASH_TRACK_0_WAVE_SPLASH = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SPLASH_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SPLASH_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_STARFIRE_TRACK_0_WAVE_STARFIRE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_STARFIRE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_STARFIRE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_TURBO_TRACK_0_WAVE_TURBO = 0,
} XACT_SOUNDBANK_COMMON_SOUND_TURBO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_TURBO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_TVSTATIC_TRACK_0_WAVE_TVSTATIC = 0,
} XACT_SOUNDBANK_COMMON_SOUND_TVSTATIC_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_TVSTATIC_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_UFO_TRACK_0_WAVE_UFO = 0,
} XACT_SOUNDBANK_COMMON_SOUND_UFO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_UFO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_WBOMB_TRACK_0_WAVE_WBOMB = 0,
} XACT_SOUNDBANK_COMMON_SOUND_WBOMB_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_WBOMB_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_WBOMBBOUNCE_TRACK_0_WAVE_WBOMBBOUNCE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_WBOMBBOUNCE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_WBOMBBOUNCE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_WBOMBFIRE_TRACK_0_WAVE_WBOMBFIRE = 0,
} XACT_SOUNDBANK_COMMON_SOUND_WBOMBFIRE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_WBOMBFIRE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_WBOMBHIT_TRACK_0_WAVE_WBOMBHIT = 0,
} XACT_SOUNDBANK_COMMON_SOUND_WBOMBHIT_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_WBOMBHIT_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_BGMUSIC_TRACK_0_WAVE_BALL = 0,
} XACT_SOUNDBANK_COMMON_SOUND_BGMUSIC_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_BGMUSIC_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_SPLASH_LOOPING_TRACK_0_WAVE_SPLASH = 0,
} XACT_SOUNDBANK_COMMON_SOUND_SPLASH_LOOPING_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_SPLASH_LOOPING_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_COMMON_SOUND_COUNTDOWN_HIGH_TRACK_0_WAVE_COUNTDOWN = 0,
} XACT_SOUNDBANK_COMMON_SOUND_COUNTDOWN_HIGH_TRACK_0_WAVE;

#define XACT_SOUNDBANK_COMMON_SOUND_COUNTDOWN_HIGH_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL1_TRACK_0_WAVE_ANIMAL1 = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL2_TRACK_0_WAVE_ANIMAL2 = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL3_TRACK_0_WAVE_ANIMAL3 = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL4_TRACK_0_WAVE_ANIMAL4 = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL4_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_ANIMAL4_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_STREAM_TRACK_0_WAVE_STREAM = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_STREAM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_STREAM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS2_TRACK_0_WAVE_TROPICS2 = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS3_TRACK_0_WAVE_TROPICS3 = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS4_TRACK_0_WAVE_TROPICS4 = 0,
} XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS4_TRACK_0_WAVE;

#define XACT_SOUNDBANK_GARDEN1_SOUND_TROPICS4_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_AIRCOND1_TRACK_0_WAVE_AIRCOND1 = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_AIRCOND1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_AIRCOND1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_CABNHUM2_TRACK_0_WAVE_CABNHUM2 = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_CABNHUM2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_CABNHUM2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_CARPARK_TRACK_0_WAVE_CARPARK = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_CARPARK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_CARPARK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_CARTON_TRACK_0_WAVE_CARTON = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_CARTON_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_CARTON_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_FREEZER1_TRACK_0_WAVE_FREEZER1 = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_FREEZER1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_FREEZER1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_ICEYAREA_TRACK_0_WAVE_ICEYAREA = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_ICEYAREA_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_ICEYAREA_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_SDRSCLOS_TRACK_0_WAVE_SDRSCLOS = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_SDRSCLOS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_SDRSCLOS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKAR_SOUND_SDRSOPEN_TRACK_0_WAVE_SDRSOPEN = 0,
} XACT_SOUNDBANK_MARKAR_SOUND_SDRSOPEN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKAR_SOUND_SDRSOPEN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_AIRCOND1_TRACK_0_WAVE_AIRCOND1 = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_AIRCOND1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_AIRCOND1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_CABNHUM2_TRACK_0_WAVE_CABNHUM2 = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_CABNHUM2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_CABNHUM2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_CARPARK_TRACK_0_WAVE_CARPARK = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_CARPARK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_CARPARK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_CARTON_TRACK_0_WAVE_CARTON = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_CARTON_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_CARTON_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_FREEZER1_TRACK_0_WAVE_FREEZER1 = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_FREEZER1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_FREEZER1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_ICEYAREA_TRACK_0_WAVE_ICEYAREA = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_ICEYAREA_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_ICEYAREA_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_SDRSCLOS_TRACK_0_WAVE_SDRSCLOS = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_SDRSCLOS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_SDRSCLOS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET1_SOUND_SDRSOPEN_TRACK_0_WAVE_SDRSOPEN = 0,
} XACT_SOUNDBANK_MARKET1_SOUND_SDRSOPEN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET1_SOUND_SDRSOPEN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_AIRCOND1_TRACK_0_WAVE_AIRCOND1 = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_AIRCOND1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_AIRCOND1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_CABNHUM2_TRACK_0_WAVE_CABNHUM2 = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_CABNHUM2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_CABNHUM2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_CARPARK_TRACK_0_WAVE_CARPARK = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_CARPARK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_CARPARK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_CARTON_TRACK_0_WAVE_CARTON = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_CARTON_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_CARTON_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_FREEZER1_TRACK_0_WAVE_FREEZER1 = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_FREEZER1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_FREEZER1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_ICEYAREA_TRACK_0_WAVE_ICEYAREA = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_ICEYAREA_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_ICEYAREA_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_SDRSCLOS_TRACK_0_WAVE_SDRSCLOS = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_SDRSCLOS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_SDRSCLOS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MARKET2_SOUND_SDRSOPEN_TRACK_0_WAVE_SDRSOPEN = 0,
} XACT_SOUNDBANK_MARKET2_SOUND_SDRSOPEN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MARKET2_SOUND_SDRSOPEN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_SOUND_ALARM2_TRACK_0_WAVE_ALARM2 = 0,
} XACT_SOUNDBANK_MUSE1_SOUND_ALARM2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE1_SOUND_ALARM2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_SOUND_ESCALATE_TRACK_0_WAVE_ESCALATE = 0,
} XACT_SOUNDBANK_MUSE1_SOUND_ESCALATE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE1_SOUND_ESCALATE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_SOUND_LARGDOOR_TRACK_0_WAVE_LARGDOOR = 0,
} XACT_SOUNDBANK_MUSE1_SOUND_LARGDOOR_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE1_SOUND_LARGDOOR_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_SOUND_LASERHUM_TRACK_0_WAVE_LASERHUM = 0,
} XACT_SOUNDBANK_MUSE1_SOUND_LASERHUM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE1_SOUND_LASERHUM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_SOUND_MUSEUMAM_TRACK_0_WAVE_MUSEUMAM = 0,
} XACT_SOUNDBANK_MUSE1_SOUND_MUSEUMAM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE1_SOUND_MUSEUMAM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE1_SOUND_ROTATING_TRACK_0_WAVE_ROTATING = 0,
} XACT_SOUNDBANK_MUSE1_SOUND_ROTATING_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE1_SOUND_ROTATING_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_SOUND_ALARM2_TRACK_0_WAVE_ALARM2 = 0,
} XACT_SOUNDBANK_MUSE2_SOUND_ALARM2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE2_SOUND_ALARM2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_SOUND_ESCALATE_TRACK_0_WAVE_ESCALATE = 0,
} XACT_SOUNDBANK_MUSE2_SOUND_ESCALATE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE2_SOUND_ESCALATE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_SOUND_LARGDOOR_TRACK_0_WAVE_LARGDOOR = 0,
} XACT_SOUNDBANK_MUSE2_SOUND_LARGDOOR_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE2_SOUND_LARGDOOR_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_SOUND_LASERHUM_TRACK_0_WAVE_LASERHUM = 0,
} XACT_SOUNDBANK_MUSE2_SOUND_LASERHUM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE2_SOUND_LASERHUM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_SOUND_MUSEUMAM_TRACK_0_WAVE_MUSEUMAM = 0,
} XACT_SOUNDBANK_MUSE2_SOUND_MUSEUMAM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE2_SOUND_MUSEUMAM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE2_SOUND_ROTATING_TRACK_0_WAVE_ROTATING = 0,
} XACT_SOUNDBANK_MUSE2_SOUND_ROTATING_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE2_SOUND_ROTATING_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_SOUND_ALARM2_TRACK_0_WAVE_ALARM2 = 0,
} XACT_SOUNDBANK_MUSE_BAT_SOUND_ALARM2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE_BAT_SOUND_ALARM2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_SOUND_ESCALATE_TRACK_0_WAVE_ESCALATE = 0,
} XACT_SOUNDBANK_MUSE_BAT_SOUND_ESCALATE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE_BAT_SOUND_ESCALATE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_SOUND_LARGDOOR_TRACK_0_WAVE_LARGDOOR = 0,
} XACT_SOUNDBANK_MUSE_BAT_SOUND_LARGDOOR_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE_BAT_SOUND_LARGDOOR_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_SOUND_LASERHUM_TRACK_0_WAVE_LASERHUM = 0,
} XACT_SOUNDBANK_MUSE_BAT_SOUND_LASERHUM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE_BAT_SOUND_LASERHUM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_SOUND_MUSEUMAM_TRACK_0_WAVE_MUSEUMAM = 0,
} XACT_SOUNDBANK_MUSE_BAT_SOUND_MUSEUMAM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE_BAT_SOUND_MUSEUMAM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_MUSE_BAT_SOUND_ROTATING_TRACK_0_WAVE_ROTATING = 0,
} XACT_SOUNDBANK_MUSE_BAT_SOUND_ROTATING_TRACK_0_WAVE;

#define XACT_SOUNDBANK_MUSE_BAT_SOUND_ROTATING_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_BASKETBALL_TRACK_0_WAVE_BASKETBALL = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_BASKETBALL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_BASKETBALL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS1_TRACK_0_WAVE_BIRDS1 = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS2_TRACK_0_WAVE_BIRDS2 = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS3_TRACK_0_WAVE_BIRDS3 = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_BIRDS3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_CITYAMB2_TRACK_0_WAVE_CITYAMB2 = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_CITYAMB2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_CITYAMB2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_DIGGER_TRACK_0_WAVE_DIGGER = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_DIGGER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_DIGGER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_DOGBARK_TRACK_0_WAVE_DOGBARK = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_DOGBARK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_DOGBARK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_KIDS_TRACK_0_WAVE_KIDS = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_KIDS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_KIDS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_LAWNMOWER_TRACK_0_WAVE_LAWNMOWER = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_LAWNMOWER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_LAWNMOWER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_ROADCONE_TRACK_0_WAVE_ROADCONE = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_ROADCONE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_ROADCONE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_SPRINK_TRACK_0_WAVE_SPRINK = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_SPRINK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_SPRINK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_STREAM_TRACK_0_WAVE_STREAM = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_STREAM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_STREAM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_SOUND_TV_TRACK_0_WAVE_TV = 0,
} XACT_SOUNDBANK_NHOOD1_SOUND_TV_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_SOUND_TV_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BASKETBALL_TRACK_0_WAVE_BASKETBALL = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BASKETBALL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BASKETBALL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS1_TRACK_0_WAVE_BIRDS1 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS2_TRACK_0_WAVE_BIRDS2 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS3_TRACK_0_WAVE_BIRDS3 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_BIRDS3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_CITYAMB2_TRACK_0_WAVE_CITYAMB2 = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_CITYAMB2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_CITYAMB2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_DIGGER_TRACK_0_WAVE_DIGGER = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_DIGGER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_DIGGER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_DOGBARK_TRACK_0_WAVE_DOGBARK = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_DOGBARK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_DOGBARK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_KIDS_TRACK_0_WAVE_KIDS = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_KIDS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_KIDS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_LAWNMOWER_TRACK_0_WAVE_LAWNMOWER = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_LAWNMOWER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_LAWNMOWER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_ROADCONE_TRACK_0_WAVE_ROADCONE = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_ROADCONE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_ROADCONE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_SPRINK_TRACK_0_WAVE_SPRINK = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_SPRINK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_SPRINK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_STREAM_TRACK_0_WAVE_STREAM = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_STREAM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_STREAM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_TV_TRACK_0_WAVE_TV = 0,
} XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_TV_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD1_BATTLE_SOUND_TV_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_BASKETBALL_TRACK_0_WAVE_BASKETBALL = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_BASKETBALL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_BASKETBALL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS1_TRACK_0_WAVE_BIRDS1 = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS2_TRACK_0_WAVE_BIRDS2 = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS3_TRACK_0_WAVE_BIRDS3 = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS3_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_BIRDS3_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_CITYAMB2_TRACK_0_WAVE_CITYAMB2 = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_CITYAMB2_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_CITYAMB2_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_DIGGER_TRACK_0_WAVE_DIGGER = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_DIGGER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_DIGGER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_DOGBARK_TRACK_0_WAVE_DOGBARK = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_DOGBARK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_DOGBARK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_KIDS_TRACK_0_WAVE_KIDS = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_KIDS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_KIDS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_LAWNMOWER_TRACK_0_WAVE_LAWNMOWER = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_LAWNMOWER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_LAWNMOWER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_ROADCONE_TRACK_0_WAVE_ROADCONE = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_ROADCONE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_ROADCONE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_SPRINK_TRACK_0_WAVE_SPRINK = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_SPRINK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_SPRINK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_STREAM_TRACK_0_WAVE_STREAM = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_STREAM_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_STREAM_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_NHOOD2_SOUND_TV_TRACK_0_WAVE_TV = 0,
} XACT_SOUNDBANK_NHOOD2_SOUND_TV_TRACK_0_WAVE;

#define XACT_SOUNDBANK_NHOOD2_SOUND_TV_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_SOUND_INTAMB1_TRACK_0_WAVE_INTAMB1 = 0,
} XACT_SOUNDBANK_SHIP1_SOUND_INTAMB1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP1_SOUND_INTAMB1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_SOUND_SEAGULLS_TRACK_0_WAVE_SEAGULLS = 0,
} XACT_SOUNDBANK_SHIP1_SOUND_SEAGULLS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP1_SOUND_SEAGULLS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_SOUND_SHIPHORN_TRACK_0_WAVE_SHIPHORN = 0,
} XACT_SOUNDBANK_SHIP1_SOUND_SHIPHORN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP1_SOUND_SHIPHORN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_SOUND_STRMRAIN_TRACK_0_WAVE_STRMRAIN = 0,
} XACT_SOUNDBANK_SHIP1_SOUND_STRMRAIN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP1_SOUND_STRMRAIN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_SOUND_THUNDER1_TRACK_0_WAVE_THUNDER1 = 0,
} XACT_SOUNDBANK_SHIP1_SOUND_THUNDER1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP1_SOUND_THUNDER1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP1_SOUND_WASH_TRACK_0_WAVE_WASH = 0,
} XACT_SOUNDBANK_SHIP1_SOUND_WASH_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP1_SOUND_WASH_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_SOUND_INTAMB1_TRACK_0_WAVE_INTAMB1 = 0,
} XACT_SOUNDBANK_SHIP2_SOUND_INTAMB1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP2_SOUND_INTAMB1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_SOUND_SEAGULLS_TRACK_0_WAVE_SEAGULLS = 0,
} XACT_SOUNDBANK_SHIP2_SOUND_SEAGULLS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP2_SOUND_SEAGULLS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_SOUND_SHIPHORN_TRACK_0_WAVE_SHIPHORN = 0,
} XACT_SOUNDBANK_SHIP2_SOUND_SHIPHORN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP2_SOUND_SHIPHORN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_SOUND_STRMRAIN_TRACK_0_WAVE_STRMRAIN = 0,
} XACT_SOUNDBANK_SHIP2_SOUND_STRMRAIN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP2_SOUND_STRMRAIN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_SOUND_THUNDER1_TRACK_0_WAVE_THUNDER1 = 0,
} XACT_SOUNDBANK_SHIP2_SOUND_THUNDER1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP2_SOUND_THUNDER1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_SHIP2_SOUND_WASH_TRACK_0_WAVE_WASH = 0,
} XACT_SOUNDBANK_SHIP2_SOUND_WASH_TRACK_0_WAVE;

#define XACT_SOUNDBANK_SHIP2_SOUND_WASH_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_ARCADE_TRACK_0_WAVE_ARCADE = 0,
} XACT_SOUNDBANK_TOY2_SOUND_ARCADE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_ARCADE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_COPTER_TRACK_0_WAVE_COPTER = 0,
} XACT_SOUNDBANK_TOY2_SOUND_COPTER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_COPTER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_CREAK_TRACK_0_WAVE_CREAK = 0,
} XACT_SOUNDBANK_TOY2_SOUND_CREAK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_CREAK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_DRAGON_TRACK_0_WAVE_DRAGON = 0,
} XACT_SOUNDBANK_TOY2_SOUND_DRAGON_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_DRAGON_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_PIANO_TRACK_0_WAVE_PIANO = 0,
} XACT_SOUNDBANK_TOY2_SOUND_PIANO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_PIANO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_PLANE_TRACK_0_WAVE_PLANE = 0,
} XACT_SOUNDBANK_TOY2_SOUND_PLANE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_PLANE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_TOYBRICK_TRACK_0_WAVE_TOYBRICK = 0,
} XACT_SOUNDBANK_TOY2_SOUND_TOYBRICK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_TOYBRICK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_TRAIN_TRACK_0_WAVE_TRAIN = 0,
} XACT_SOUNDBANK_TOY2_SOUND_TRAIN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_TRAIN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOY2_SOUND_WHISTLE_TRACK_0_WAVE_WHISTLE = 0,
} XACT_SOUNDBANK_TOY2_SOUND_WHISTLE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOY2_SOUND_WHISTLE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_ARCADE_TRACK_0_WAVE_ARCADE = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_ARCADE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_ARCADE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_COPTER_TRACK_0_WAVE_COPTER = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_COPTER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_COPTER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_CREAK_TRACK_0_WAVE_CREAK = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_CREAK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_CREAK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_DRAGON_TRACK_0_WAVE_DRAGON = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_DRAGON_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_DRAGON_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_PIANO_TRACK_0_WAVE_PIANO = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_PIANO_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_PIANO_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_PLANE_TRACK_0_WAVE_PLANE = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_PLANE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_PLANE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_TOYBRICK_TRACK_0_WAVE_TOYBRICK = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_TOYBRICK_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_TOYBRICK_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_TRAIN_TRACK_0_WAVE_TRAIN = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_TRAIN_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_TRAIN_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_TOYLITE_SOUND_WHISTLE_TRACK_0_WAVE_WHISTLE = 0,
} XACT_SOUNDBANK_TOYLITE_SOUND_WHISTLE_TRACK_0_WAVE;

#define XACT_SOUNDBANK_TOYLITE_SOUND_WHISTLE_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_SOUND_BATS_TRACK_0_WAVE_BATS = 0,
} XACT_SOUNDBANK_WILD_WEST1_SOUND_BATS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST1_SOUND_BATS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_SOUND_COYOTE1_TRACK_0_WAVE_COYOTE1 = 0,
} XACT_SOUNDBANK_WILD_WEST1_SOUND_COYOTE1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST1_SOUND_COYOTE1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_SOUND_EAGLE1_TRACK_0_WAVE_EAGLE1 = 0,
} XACT_SOUNDBANK_WILD_WEST1_SOUND_EAGLE1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST1_SOUND_EAGLE1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_SOUND_MINEDRIP_TRACK_0_WAVE_MINEDRIP = 0,
} XACT_SOUNDBANK_WILD_WEST1_SOUND_MINEDRIP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST1_SOUND_MINEDRIP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_SOUND_RATTLER_TRACK_0_WAVE_RATTLER = 0,
} XACT_SOUNDBANK_WILD_WEST1_SOUND_RATTLER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST1_SOUND_RATTLER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_SOUND_TOWNBELL_TRACK_0_WAVE_TOWNBELL = 0,
} XACT_SOUNDBANK_WILD_WEST1_SOUND_TOWNBELL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST1_SOUND_TOWNBELL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST1_SOUND_TUMBWEED_TRACK_0_WAVE_TUMBWEED = 0,
} XACT_SOUNDBANK_WILD_WEST1_SOUND_TUMBWEED_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST1_SOUND_TUMBWEED_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_SOUND_BATS_TRACK_0_WAVE_BATS = 0,
} XACT_SOUNDBANK_WILD_WEST2_SOUND_BATS_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST2_SOUND_BATS_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_SOUND_COYOTE1_TRACK_0_WAVE_COYOTE1 = 0,
} XACT_SOUNDBANK_WILD_WEST2_SOUND_COYOTE1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST2_SOUND_COYOTE1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_SOUND_EAGLE1_TRACK_0_WAVE_EAGLE1 = 0,
} XACT_SOUNDBANK_WILD_WEST2_SOUND_EAGLE1_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST2_SOUND_EAGLE1_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_SOUND_MINEDRIP_TRACK_0_WAVE_MINEDRIP = 0,
} XACT_SOUNDBANK_WILD_WEST2_SOUND_MINEDRIP_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST2_SOUND_MINEDRIP_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_SOUND_RATTLER_TRACK_0_WAVE_RATTLER = 0,
} XACT_SOUNDBANK_WILD_WEST2_SOUND_RATTLER_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST2_SOUND_RATTLER_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_SOUND_TOWNBELL_TRACK_0_WAVE_TOWNBELL = 0,
} XACT_SOUNDBANK_WILD_WEST2_SOUND_TOWNBELL_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST2_SOUND_TOWNBELL_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_SOUNDBANK_WILD_WEST2_SOUND_TUMBWEED_TRACK_0_WAVE_TUMBWEED = 0,
} XACT_SOUNDBANK_WILD_WEST2_SOUND_TUMBWEED_TRACK_0_WAVE;

#define XACT_SOUNDBANK_WILD_WEST2_SOUND_TUMBWEED_TRACK_0_WAVE_COUNT 1

typedef enum
{
    XACT_CATEGORY_BGMUSIC = 0,
} XACT_CATEGORY;

#define XACT_CATEGORY_COUNT 1

#endif // __XACT_PROJECT_REVOLT__
