//-----------------------------------------------------------------------------
// File: MenuText.h
//
// Desc: 
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------
#ifndef MENUTEXT_H
#define MENUTEXT_H

#include "revolt.h"
#include "typedefs.h"

//-------------------------------------------------------------------------------
// Language enummeration
//-------------------------------------------------------------------------------

// Languages
enum LanguageEnum {
    ENGLISH,
    FRENCH,
    GERMAN,
    ITALIAN,
    SPANISH,

    NLANGS,
    LANG_LAST = NLANGS

};

//-------------------------------------------------------------------------------
// Strings
//-------------------------------------------------------------------------------
enum TITLE_TEXT_STRING
{
    TEXT_LANGUAGE = -2,
    TEXT_NONE = -1,

// Menu Titles
    TEXT_REVOLT = 0,

	// Top level menu
	TEXT_PLAYLIVE,
	TEXT_SINGLEPLAYER,
	TEXT_MULTIPLAYER,
	TEXT_SYSTEMLINK,
	TEXT_OPTIONS,

	// Play Live menu
	TEXT_QUICKMATCH,
	TEXT_FINDMATCH,
	TEXT_FRIENDS,
	TEXT_CREATEMATCH,
	TEXT_STATISTICS,

    // Menu Titles
    TEXT_SELECTRACE,
    TEXT_ENTERNAME,
    TEXT_CHOOSECAR,
    TEXT_SELECTTRACK,
    TEXT_CHOOSECUP,
    TEXT_SUMMARY,
    TEXT_CONNECTION,
    TEXT_RENDERSETTINGS,
    TEXT_MULTITYPE,
    TEXT_WAITINGROOM,
    TEXT_GAMEALREADYSTARTED,
    TEXT_CONTROLLER,
    TEXT_MULTISELECT,

// Title Screen
    TEXT_STARTRACE,
    TEXT_BESTTIMES,
    TEXT_SECRETS,
    TEXT_TRACKEDITOR,
//    TEXT_OPTIONS,
    TEXT_QUIT,

	// Select Rave
    TEXT_SINGLERACE,
    TEXT_TIMETRIAL,
    TEXT_PRACTICE,
    TEXT_BATTLETAG,
    TEXT_STUNTAREA,

// Start Race
    TEXT_CHAMPIONSHIP2,
    TEXT_SINGLERACE2,
    TEXT_CLOCKWORKRACE2,
    TEXT_BATTLE2,
    TEXT_TIMETRIAL2,
    TEXT_PRACTICE2,
    TEXT_TRAINING2,
//    TEXT_MULTIPLAYER2,
    TEXT_EDITMODE2,
    TEXT_CALCSTATS2,

// Select Car
    TEXT_SELECTCAR,

// Select Track
    TEXT_SELECTTRACK2,
    TEXT_SELECTMIRROR,
    TEXT_SELECTREVERSE,
    TEXT_NUMCARS,
    TEXT_NUMLAPS,
    TEXT_LENGTH,

// Select Cup
    TEXT_BRONZECUP,
    TEXT_SILVERCUP,
    TEXT_GOLDCUP,
    TEXT_PLATINUMCUP,

// Training Mode
    TEXT_TRAININGMODE,
    TEXT_BASICCORNERING,
    TEXT_ADVANCEDCORNERING,
    TEXT_YOUR1STSTUNTS,

// Options
    TEXT_GAMESETTINGS,
    TEXT_VIDEOSETTINGS,
    TEXT_AUDIOSETTINGS,
    TEXT_CONTROLLERSETTINGS,
    TEXT_LOADSAVERECORDS,
    TEXT_CREDITS,

// Game Settings
    TEXT_NUMBEROFCARS,
    TEXT_RANDOM_CARS,
    TEXT_RANDOM_TRACK,
    TEXT_PICKUPS,
    TEXT_NUMBEROFLAPS,
    TEXT_TIMEOFBOMBTAG,
    TEXT_DIFFICULTY,
    TEXT_CARACCESS,
    TEXT_GHOSTTYPE,
    TEXT_COLLISION,
    TEXT_UNITS,

// Name entry
    TEXT_NAMEENTRY,

// Misc.
    TEXT_ON,
    TEXT_OFF,
    TEXT_YES,
    TEXT_NO,
    TEXT_EASY,
    TEXT_MEDIUM,
    TEXT_HARD,
    TEXT_VERYHARD,
    TEXT_VERTICAL,
    TEXT_HORIZONTAL,

// Video Settings
    TEXT_SCREENRES,
    TEXT_TEXTURE,
    TEXT_SHINYNESS,
    TEXT_SHADOWS,
    TEXT_DRAWDEVICE,
    TEXT_BRIGHTNESS,
    TEXT_CONTRAST,
    TEXT_DRAWDIST,
    TEXT_REFLECTIONS,
    TEXT_INSTANCES,
    TEXT_SKIDMARKS,
    TEXT_LIGHTS,
    TEXT_AUTOMATIC,
    TEXT_UNAVAILABLE,
    TEXT_ANTIALIAS,
    TEXT_VSYNC,
    TEXT_SHOW_FPS,
    TEXT_TEXTUREFILTER,
    TEXT_MIPMAP,
    TEXT_WIREFRAME,
    TEXT_CARBBOXES,
    TEXT_PARTICLES,
    TEXT_SMOKE,
    TEXT_HIRES,
    TEXT_SCREENSPLIT,

// Audio Settings
    TEXT_MUSIC_ON,
    TEXT_SFXVOLUME,
    TEXT_MUSICVOLUME,
    TEXT_SFXTEST,
    TEXT_MUSICTEST,
    TEXT_SFX_CHANNELS,
    TEXT_AUDIO,
    TEXT_STEREO,
    TEXT_MONO,

// Time Trial
    TEXT_VIEWRECORDS,
    TEXT_SAVERECORDS,
    TEXT_RACE,

    TEXT_RECORDS,

// MultiPlayer
    TEXT_MP_STARTGAME,
    TEXT_MP_JOINGAME,
    TEXT_MP_WAITFORLOBBY,
    TEXT_MP_SELECTGAME,
    TEXT_HOSTCOMPUTER,
    TEXT_LOBBYCONTINUE,
    TEXT_LOBBYQUIT,
    TEXT_NUMPLAYERS,
    TEXT_PACKET_TYPE,
    TEXT_PROTOCOL_TYPE,
    TEXT_GAME_SEARCH,
    TEXT_GAME_JOIN,
    TEXT_GAME_LIST,
    TEXT_NEXT_TRACK,

// Cars Allowed
    TEXT_ALLOW_DEFAULT,
    TEXT_ALLOW_BRONZE,
    TEXT_ALLOW_SILVER,
    TEXT_ALLOW_GOLD,
    TEXT_ALLOW_SPECIAL,

// Replay load/save
    TEXT_LOAD_REPLAY,
    TEXT_SAVE_REPLAY,

// In-game menu
    TEXT_RESUME_RACE,
    TEXT_CONTINUE_CHAMP,
    TEXT_END_CHAMP,
    TEXT_GIVEUP_CHAMP,
    TEXT_RESTART_RACE,
    TEXT_RESTART_REPLAY,
    TEXT_QUIT_RACE,
    TEXT_VIEW_REPLAY,

// Controller
    TEXT_CONTROLLERSELECT,
    TEXT_CONTROLLERCONFIG,
    TEXT_STEERING_DEADZONE,
    TEXT_STEERING_RANGE,
    TEXT_STEERING,
    TEXT_CONTROLLERDEFAULT,
    TEXT_CONTROLLERCONFIGNUM,

// Misc
    TEXT_DEMO_MESSAGE,
    TEXT_PLAYERNUM,
    TEXT_SAVECARINFOSINGLE,
    TEXT_SAVECARINFOMULTIPLE,
    TEXT_SAVECURRENTCARINFO,
    TEXT_CLEARSECRETS,
    TEXT_MODE,
    TEXT_MODE_SIMULATION,
    TEXT_MODE_ARCADE,
    TEXT_MODE_CONSOLE,
    TEXT_PLAYMODE_KIDS,
    TEXT_MPH,
    TEXT_SCALEDMPH,
    TEXT_FPM,
    TEXT_KPH,
    TEXT_SCALEDKPH,

// Win/lose sequence strings
    TEXT_YOU_CAME,
    TEXT_TRY_TO_COME_HIGHER_TO, 
    TEXT_UNLOCK_THE_NEXT_CHALLENGE,
    TEXT_BRONZE_CUP,
    TEXT_SILVER_CUP,
    TEXT_GOLD_CUP,
    TEXT_SPECIAL_CUP,
    TEXT_IS_UNLOCKED,
    TEXT_MIRRORED_TRACKS,
    TEXT_REVERSED_TRACKS,
    TEXT_HAVE_BEEN_UNLOCKED,
    TEXT_NEW_DELIVERY_OF_CARS,
    TEXT_YOU_HAVE_UNLOCKED,
    TEXT_NEW_CARS,
    TEXT_FIRST,
    TEXT_SECOND,
    TEXT_THIRD,

//---------------
// Memory card
//---------------
    TEXT_MEMORY_CARD,
    TEXT_ERROR,
    TEXT_WARNING,
    TEXT_ARE_YOU_SURE,
    TEXT_LOAD_SETTINGS,
    TEXT_SAVE_SETTINGS,
    TEXT_LOAD_TRACKS,
    TEXT_LOADING,
    TEXT_SAVING,
    TEXT_MCARD_SPACES,
    TEXT_LOAD_GHOST,
    TEXT_SAVE_GHOST,
    TEXT_MEMORY_CONTINE,
    TEXT_MEMORY_CONT_NO_SAVE,
    TEXT_MEMORY_CONT_NO_LOAD,
    TEXT_MEMORY_FORMAT,
    TEXT_MEMORY_REPAIR,
    TEXT_MEMORY_MANAGE,
    TEXT_MEMORY_SWAP,
    TEXT_MEMORY_RETRY,
    TEXT_REPAIR_ATTEMPT,
    TEXT_REPAIR_FAIL,
    TEXT_REPAIR_SUCC,
    TEXT_MCARD_BIG_SPACES,
    TEXT_DELETE_MEMORY_BLOCK,

    // Championship summary screen
    TEXT_CHAMP_FINISH_RACE1,
    TEXT_CHAMP_FINISH_RACE2,
    TEXT_CHAMP_FINISH_CHAMP1,
    TEXT_CHAMP_FINISH_CHAMP2,
    TEXT_CHAMP_FINISH_CHAMP3,
    TEXT_CHAMP_FINISH_CHAMP4,

    // N64 Specifics MEM_CARD messages
    TEXT_N64_MEMCARD_OK,            
    TEXT_N64_MEMCARD_DETECTED,         
    TEXT_N64_MEMCARD_FIRST,         
    TEXT_N64_MEMCARD_NEW,           
    TEXT_N64_MEMCARD_INVALID,       
    TEXT_N64_MEMCARD_FULL1,         
    TEXT_N64_MEMCARD_FULL2,         
    TEXT_N64_MEMCARD_DISCONECTED,   
    TEXT_N64_MEMCARD_NOCONTROLLER,  
    TEXT_N64_MEMCARD_NOGAMEFOUND,   
    TEXT_N64_MEMCARD_SWITCHTOMEMPAK,
    TEXT_N64_MEMCARD_INSERTRUMBLE,  
    TEXT_N64_MEMCARD_WARNINGFORMAT, 
    TEXT_N64_MEMCARD_REPAIRQUESTION, 
    TEXT_N64_MEMCARD_GAMEPROGRESS, 
    TEXT_N64_MEMCARD_GHOSTCAR, 
    TEXT_N64_MEMCARD_USERTRACKS, 
    TEXT_N64_MEMCARD_OVERWRITE,

    // Specifics MEM_CARD messages, shared N64 & PSX ??
    TEXT_MEMCARD_CONFIRM,

//---------------
// MenuDraw.cpp
//---------------
    TEXT_MIRROR_ABREV,
    TEXT_REVERSE_ABREV,
    TEXT_MIRROR_ABREV_PARENTHESIS,
    TEXT_REVERSE_ABREV_PARENTHESIS,

// Select Car
    TEXT_CAR_CLASS,
    TEXT_CAR_RATING,
    TEXT_CAR_SPEED,
    TEXT_CAR_ACC,
    TEXT_CAR_WEIGHT,
    TEXT_CAR_TRANS,

    TEXT_CAR_CLASS_ELECTRIC,
    TEXT_CAR_CLASS_GLOW,
    TEXT_CAR_CLASS_SPECIAL,

    TEXT_CAR_RATING_ROOKIE,
    TEXT_CAR_RATING_AMATEUR,
    TEXT_CAR_RATING_ADVANCED,
    TEXT_CAR_RATING_SEMI_PRO,
    TEXT_CAR_RATING_PRO,

    TEXT_CAR_TRANS_4WD,
    TEXT_CAR_TRANS_RWD,
    TEXT_CAR_TRANS_FWD,

// Load Screen Info
    TEXT_UNKNOWN,
    TEXT_LOCKED,

// Frontend Summary
    TEXT_PLAYER_SINGULAR,
    TEXT_PLAYER_PLURAL,

// Select Mode
    TEXT_SIMULATION_HELPSTRING,
    TEXT_ARCADE_HELPSTRING,
    TEXT_CONSOLE_HELPSTRING,
    TEXT_KIDS_HELPSTRING,

// Controller Config
    TEXT_CONTROL_ACC,
    TEXT_CONTROL_REV,
    TEXT_CONTROL_FIRE,
    TEXT_CONTROL_FLIP,
    TEXT_CONTROL_REPOSITION,
    TEXT_CONTROL_CHANGECAMERA,
    TEXT_CONTROL_REARVIEW,
    TEXT_CONTROL_PAUSE,

// Draw Progress
    TEXT_SECRETS_TRACKS,
    TEXT_SECRETS_WONRACE_TOP,
    TEXT_SECRETS_WONRACE_BOTTOM,
    TEXT_SECRETS_NORM,
    TEXT_SECRETS_REV,
    TEXT_SECRETS_MIRR,
    TEXT_SECRETS_STARS,

// Load Screen Info
    TEXT_LOADSCREEN_GAMEMODE,
    TEXT_LOADSCREEN_STAGE,
    TEXT_LOADSCREEN_TRACK,
    TEXT_CAR,
    TEXT_LOADSCREEN_WONRACE,
    TEXT_LOADSCREEN_FOUNDSTAR,
    TEXT_LOADSCREEN_STARSCOLLECTED,
    TEXT_OF,
    TEXT_LOADSCREEN_BEATEN,
    TEXT_LOADSCREEN_CHALLENGETIME,

    TEXT_CONFIRM_GIVEUP_YOUHAVE,
    TEXT_CONFIRM_GIVEUP_TRYLEFT,
    TEXT_CONFIRM_GIVEUP_TRIESLEFT,
    
//---------------
// Panel
//---------------

// Position
    TEXT_ST_NUMABBREV,
    TEXT_ND_NUMABBREV,
    TEXT_RD_NUMABBREV,
    TEXT_TH_NUMABBREV,

// Championship result
    TEXT_CHAMP_QUALIFIED1,      
    TEXT_CHAMP_QUALIFIED2,         
    TEXT_CHAMP_FINISHED1,      
    TEXT_CHAMP_FINISHED2,
    TEXT_CHAMP_FAILURE,
    TEXT_CHAMP_ROWTITLE_CAR,
    TEXT_CHAMP_ROWTITLE_POINTS,

// Panel
    TEXT_PANEL_BESTLAP,
    TEXT_PANEL_LASTLAP,
    TEXT_PANEL_LAPTIME,
    TEXT_PANEL_RACETIME,
    TEXT_PANEL_LAPCOUNTER,
    TEXT_PANEL_GHOSTSPLIT,
    TEXT_PANEL_GHOSTTIME,
    TEXT_PANEL_CHALLENGETIME,
    TEXT_PANEL_CHALLENGE_BEATEN,
    TEXT_PANEL_TAGTIME,
    TEXT_PANEL_BATTLE_RESULTS,
    TEXT_PANEL_RACE_RESULTS,

//---------------
// Menudat2.cpp
//---------------

//Confirmation strings
    TEXT_MENU_CONFIRM_QUIT,
    TEXT_MENU_CONFIRM_RESTART,
    TEXT_MENU_CONFIRM_GENERIC,
    TEXT_MENU_CONFIRM_REALLY,
    TEXT_MENU_CONFIRM_PRETEND,


//---------------
// Compete.cpp
//---------------
    TEXT_COMPETE_CUP_DEFAULT,   
    TEXT_COMPETE_CUP_BRONZE,   
    TEXT_COMPETE_CUP_SILVER,   
    TEXT_COMPETE_CUP_GOLD,     
    TEXT_COMPETE_CUP_PLATINUM, 

    TEXT_COMPETE_GAMEOVER,

//---------------
// TitleScr.cpp
//---------------
    TEXT_BONUS_NEWCARS,
    TEXT_BONUS_REVERSE,
    TEXT_BONUS_MIRROR,
    TEXT_BONUS_REVMIR,
    TEXT_BONUS_COCKWORK,


//---------------
// gameloop.cpp
//---------------
    TEXT_PRESS_START_BUTTON,
    TEXT_PRESS_START_CONTINUE,
    TEXT_PRESS_START_CONTINUE_CENTERED,
    TEXT_PAUSE,

//---------------
// Credit.cpp
//---------------

    TEXT_CREDIT_AGAMEBY,
    TEXT_CREDIT_PROJECT_MANAGER,
    TEXT_CREDIT_LEAD_CODERS,
    TEXT_CREDIT_PC_CODERS,
    TEXT_CREDIT_N64_CODERS,
    TEXT_CREDIT_PSX_CODERS,
    TEXT_CREDIT_RENDER,
    TEXT_CREDIT_PHYSICS,
    TEXT_CREDIT_AI,
    TEXT_CREDIT_TE,
    TEXT_CREDIT_MISC_CODERS,
    TEXT_CREDIT_LEAD_ARTIST,
    TEXT_CREDIT_TRACK_MODELLING,
    TEXT_CREDIT_TRACK_TEXTURES,
    TEXT_CREDIT_CAR_ARTWORK,
    TEXT_CREDIT_CONCEPT,
    TEXT_CREDIT_LEAD_DESIGN,
    TEXT_CREDIT_DESIGN,
    TEXT_CREDIT_SFX,
    TEXT_CREDIT_MUSIC,
    TEXT_CREDIT_SFX_N64,
    TEXT_CREDIT_QA_MANAGER,
    TEXT_CREDIT_QA_TEAM,
    TEXT_CREDIT_NET_MANAGER,
    TEXT_CREDIT_PC_TECH,
    TEXT_CREDIT_CREATIVE_DIRECTOR,
    TEXT_CREDIT_ART_DIRECTOR,
    TEXT_CREDIT_DESIGN_DIRECTOR,
    TEXT_CREDIT_AUDIO_DIRECTOR,
    TEXT_CREDIT_BUISNESS_DIRECTOR,
    TEXT_CREDIT_TECHNICAL_DIRECTOR,
    TEXT_CREDIT_SPECIAL_THANKS,

    TEXT_CREDIT_FINAL00,
    TEXT_CREDIT_FINAL01,
    TEXT_CREDIT_FINAL02,
    TEXT_CREDIT_FINAL03,
    TEXT_CREDIT_FINAL04,
    TEXT_CREDIT_FINAL05,
    TEXT_CREDIT_FINAL06,
    TEXT_CREDIT_FINAL07,
    TEXT_CREDIT_FINAL08,
    TEXT_CREDIT_FINAL09,
    TEXT_CREDIT_FINAL10,
    TEXT_CREDIT_FINAL11,
    TEXT_CREDIT_FINAL12,
    TEXT_CREDIT_FINAL13,
    TEXT_CREDIT_FINAL14,
    TEXT_CREDIT_FINAL15,

// ------------
// Track Editor
//-------------
    TEXT_MODE_MODULES,
    TEXT_MODE_PICKUPS,
    TEXT_MODE_ADJUST,
    TEXT_MODE_SAVE,
    TEXT_MODE_NEW,
    TEXT_MODE_LOAD,
    TEXT_MODE_EXPORT,
    TEXT_MODE_QUIT,
    TEXT_MODE_PLACING,
    TEXT_MODE_DELETING,

    //mode status words for bottom left of sprue
    TEXT_MODE_MENU,
    TEXT_DIALOG_WARNING,
    TEXT_DIALOG_QUESTION,
    TEXT_DIALOG_INFO,

    //module group names
    TEXT_GROUP_START,
    TEXT_GROUP_STRAIGHT,
    TEXT_GROUP_DIP,
    TEXT_GROUP_HUMP,
    TEXT_GROUP_SQUARE_CORNER,
    TEXT_GROUP_ROUND_CORNER,
    TEXT_GROUP_DIAGONAL,
    TEXT_GROUP_BANK,
    TEXT_GROUP_RUMBLE,
    TEXT_GROUP_NARROW,
    TEXT_GROUP_PIPE,
    TEXT_GROUP_BRIDGE,
    TEXT_GROUP_CROSSROAD,
    TEXT_GROUP_JUMP,
    TEXT_GROUP_CHICANE,
    
    //query dialog
    TEXT_OPTION_YES,
    TEXT_OPTION_NO,

    //compilation status
    TEXT_COMPILE_STAGE_1,
    TEXT_COMPILE_STAGE_2,
    TEXT_COMPILE_STAGE_3,
    TEXT_COMPILE_STAGE_4,
    TEXT_COMPILE_STAGE_5,
    TEXT_COMPILE_STAGE_6,
    TEXT_COMPILE_STAGE_7,
    TEXT_COMPILE_STAGE_8,
    TEXT_COMPILE_STAGE_9,
    TEXT_COMPILE_STAGE_10,
    TEXT_COMPILE_STAGE_11,
    TEXT_COMPILE_STAGE_12,
    TEXT_COMPILE_FINISHED,

    TEXT_CONFIRM_SAVE,

    //default description for all tracks ???
    TEXT_DEFAULT_TRACK_NAME,

    TEXT_PICKUPS_PLACED,

    TEXT_ADJUST_POSITION,
    TEXT_ADJUST_SIZE,

    //warnings & errors
    TEXT_QUERY_SAVE,
    TEXT_QUERY_SAVE_RETRY,
    TEXT_QUERY_OVERWRITE,
    TEXT_QUERY_DELETE,
    TEXT_QUERY_KEEP_CHANGES,
    TEXT_INFO_SAVED,
    TEXT_WARNING_SAVE_ERROR,
    TEXT_WARNING_TRACK_INVALID1,
    TEXT_WARNING_TRACK_INVALID2,
    TEXT_WARNING_TRACK_INVALID3,
    TEXT_WARNING_TRACK_INVALID4,
    TEXT_WARNING_TRACK_INVALID5,
    TEXT_WARNING_NO_START,
    TEXT_WARNING_MULTIPLE_STARTS,
    
//-----------------
// PC missed stuff!
//-----------------

    TEXT_CONTROL_LEFT = 448,
    TEXT_CONTROL_RIGHT,
    TEXT_CONTROL_HORN,
    TEXT_TRYAGAIN,
    TEXT_DEMO,
    TEXT_LOADINGFRONTEND,
    TEXT_LOADINGCREDITS,
    TEXT_LOADINGGAMEGAUGE,
    TEXT_RACERS,
    TEXT_CPUOPPONENT,
    TEXT_RANDOM,
    TEXT_STATUS,
    TEXT_READY,
    TEXT_NOTREADY,
    TEXT_HITTABTOSTART,
    TEXT_MULTIGAMETERMINATED,
    TEXT_WAITINGFOR,
    TEXT_WAITINGFORHOST,
    TEXT_HOST,
    TEXT_TRACK,
    TEXT_GAME,
    TEXT_WRONGVERSION,
    TEXT_FULL,
    TEXT_RECORD,
    TEXT_SCALED,
    TEXT_FINISHED,
    TEXT_STARTED,
    TEXT_OPEN,
    TEXT_REPLAY,
    TEXT_GALLERY,
    TEXT_LOCAL,
    TEXT_DOWNLOAD,

    TEXT_NTEXTS
};


//-------------------------------------------------------------------------------
// Globals... 
//-------------------------------------------------------------------------------
extern char *gTitleScreen_Text[];

//-------------------------------------------------------------------------------
// Function Macros and prototypes 
//-------------------------------------------------------------------------------

#define OLD_MENU_TEXT

// ifndef (OLD_MENU_TEXT) 
//  => _MUST_ Make a call to LANG_LoadStrings() or _WILL_ Crash
//------------------------------------------------------------------
#define TEXT_TABLE(index) (gTitleScreen_Text[(index)])


extern unsigned LANG_GetLanguage();
extern bool     LANG_LoadStrings(unsigned uLang);
extern char *LangNames[NLANGS];

#endif // MENUTEXT_H

